### PR TITLE
fixing race condition in the videoroom plugin

### PR DESCRIPTION
**Pull request by cppdev-1**
The reason: thread tries to clear the mutex whilst another thread is holding it.

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @cppdev-1! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Comment by lminiero** [comment]
Mh I don't think this PR can't be accepted, sorry. It introduces a new global mutex for updating stuff, which seems way overkill. If race conditions on critical paths are the issue, they should be solved with careful usages of the existing mutexes (which is what we've tried to do so far).

**Comment by cppdev-1** [comment]
@lminiero In fact, I've tried to use janus_videoroom_session->mutex as a good alternative to global mutex, but I had a deadlock with it. Also, there was possibility of crash in another place. According to my tests there were no significant drawbacks against global mutex. Only session destruction time increased slighly.

**Comment by lminiero** [comment]
Closing as we have a separate fix for the issue. Thanks for bringing it to our attention!

**Pull request closed without merging**
