### PR TITLE
Added supervisor sample to the documentation

### PR DESCRIPTION
**Pull request by eduardomb**

### CODE REVIEW

**Comment by lminiero** [comment]
I'm not familiar with supervisor but I'm sure this will be helpful to a lot of people, thanks!
Before we can merge, can you sign our [CLA](https://cla.conf.meetecho.com/janus/) at the end of the page?

**Comment by lminiero** [comment]
If you'd rather not sign, let me know and I'll copy the changes you made to the documentation myself.

**Comment by eduardomb** [comment]
CLA signed!

**Comment by lminiero** [comment]
Tnx! Merging then.

**Pull request merged**
