### PR TITLE
Add new listforwarders request

### PR DESCRIPTION
**Pull request by amnonbb**

### CODE REVIEW

**Comment by lminiero** [comment]
Please update with the new `JANUS_CHECK_SECRET` @ploxiln added and we just merged.
Besides, could you write a small description of what the code aims to do, and an example of request/response?

Thanks!

**Comment by amnonbb** [comment]
I'm shortly describe the problem and examples i'll add later.
If you really use rtp forward with many participants, you have to remember every stream id that you get when start forward. These ID's you will need when you want to stop forward.

**Comment by lminiero** [comment]
Why did you close it? Not interested in merging this anyore or was it a mistake?

**Comment by amnonbb** [comment]
I supposed i did something wrong.. :|
I wanted to merge source master to my fork and make new PR.
I don't know other ways to do.
I don't have an experience with git, sry

**Pull request closed without merging**
