### PR TITLE
transports/http: avoid segfault on JSON error

### PR DESCRIPTION
**Pull request by tmatth**
Refs #2626

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! This feels like a check that should be added to the other transports (and event handlers?) as well, in case, since they'd suffer from the same issue with overly large objects.

**Comment by tmatth** [comment]
> Thanks! This feels like a check that should be added to the other transports (and event handlers?) as well, in case, since they'd suffer from the same issue with overly large objects.

Yeah that's why I marked as draft, if @winlinvip is able to confirm that this fixes the one crash there are probably a lot of other places where jansson's output needs to be checked for NULL, as unlike glib it won't abort on e.g. a failed allocation (or even invalid JSON).

**Comment by lminiero** [comment]
I doubt we'll get feedback from the OP, and I think these are good checks to have: since they seem straightforward enough, I can take care of them all in a dedicated commit.

**Comment by lminiero** [comment]
The above commit should address them all, so I'll close this PR. Thanks!

**Comment by winlinvip** [comment]
Sorry, I'm a bit quit busy these days, I will check it now.

**Comment by winlinvip** [comment]
I did some benchmarks, NO crash now, thanks~

* For 4CPU, although the load is very high, and some sessions were timeout, but no crash now.
* For 8CPU, the max threads can be about 1800, but lots of timeout and decrease to about 900 threads. No crash now.

It's possible to publish more streams to Janus than before. I got some data but I'm not sure it's ok to show it, but I think the perf and benchmark snapshot is OK, which might be useful for performance improvement.

The bellow is benchmark for 4CPUs, about 900 threads of Janus:

image

**Comment by atoppi** [comment]
@winlinvip thanks for sharing your findings.
I have some observations:
1) could you please inspect the `janus_ice_cb_nice_recv` function with `annotate` to find the hot path ? We suspect that the very high usage is due to nack handling
2) `srtp_aes_encyot` as the second highest function makes me suspect that you are testing with a VM / srtp library without hw acceleration for AES-NI
3) also the high usage from `srtp_aes_encrypt` in a publishers-only test could mean that you are generating **A LOT** of RTCP traffic and that might be explained by **A LOT** of nacks sent by Janus (network loss? the bench tool struggling?)
4) could you share the remaining data that you're unsure to post here? Please drop an email to dev@meetecho.com

**Comment by atoppi** [comment]
Also when expecting such a high load on a server, it would be better to tune the `event_loops` setting in `janus.jcfg` to 
**N x #CORES**
with N >= 1

**Comment by winlinvip** [comment]
@atoppi Thanks for your help~

1. About the performance refine, I'm really sorry, because it takes a lot of time to test and analysis. I think it's better way, if you  use [srs-bench](https://github.com/ossrs/srs-bench/tree/feature/rtc#janus) to benchmark locally, or other tools. 
2. I will try `event_loops` to 8 and give some feedback.

**Comment by winlinvip** [comment]
@atoppi It works! Thanks very much.

For 8 CPU server, janus is 779% and load is 10, and threads is 28. The data is much much better than before.

I will email you the compare data to dev@meetecho.com

Thanks~

**Pull request closed without merging**
