### PR TITLE
Support 407 response for REGISTER

### PR DESCRIPTION
**Pull request by unomemento**
Handle 407 response for register (similarly to the handling of 401)

### CODE REVIEW

**Comment by lminiero** [comment]
Looks useful, thanks for working on this! In order to be able to merge this, can you sign our CLA at the end of [this page](https://cla.conf.meetecho.com/janus/)?

**Comment by unomemento** [comment]
Thanks, I have signed the CLA

**Comment by lminiero** [comment]
Thanks, merging then!

**Comment by unomemento** [comment]
Thanks a lot!

**Pull request merged**
