### PR TITLE
Lock forwarder mutex before using forwarder hash table.

### PR DESCRIPTION
**Pull request by drichardson**

### CODE REVIEW

**Comment by lminiero** [comment]
Looks reasonable, thanks! Can you sign our [CLA](https://cla.conf.meetecho.com/janus/) so that I can merge this after a quick series of tests?

**Comment by lminiero** [comment]
If you'd rather not sign, let me know and I'll copy the changes you made to the code myself.

**Comment by drichardson** [comment]
Yes, please copy the changes for this commit, since I need to clear the legal stuff with my employer.

**Comment by lminiero** [comment]
Done, tnx :+1:

**Pull request closed without merging**
