### PR TITLE
sctp: Fix segmentation fault

### PR DESCRIPTION
**Pull request by uxmaster**
after destroying SCTP association.

### CODE REVIEW

**Comment by lminiero** [comment]
Hi, not sure what moving the unlock/lock achieves? Why do you think this fixes the segfault you're experiencing?

**Comment by lminiero** [comment]
Just noticed that the unlock/lock around ```janus_dtls_send_sctp_data``` is unneeded. I guess it was there because of how the feature worked in early revisions, and where it could lead to deadlock for trying to lock a mutex already locked. That's no longer the case with the current code, so I'll remove them.

**Comment by uxmaster** [comment]
Actually, I'm not so sure. I have experienced segfault just after
```
[152834908] Destroying SCTP association
[152834908] Data from SCTP to DTLS stack: 20 bytes
[152834908] Data from SCTP to DTLS stack: 20 bytes
[152834908] WebRTC resources freed
```
`janus_dtls_send_sctp_data` uses `sctp->dtls`, thus without the lock `janus_sctp_association_destroy` could free it in the meantime...

Now, after your commit, it is locked, so it should be OK.

**Comment by lminiero** [comment]
Ok, let me know if that's not the case.

**Pull request closed without merging**
