### PR TITLE
sip: Make the SIP proxy optional

### PR DESCRIPTION
**Pull request by saghul**
When not specified Sofia-SIP will conduct the standard (RFC3263) lookup
mechanism.

### CODE REVIEW

**Comment by lminiero** [comment]
While I agree that the proxy can be made optional to allow for the scenario you envisaged, not all deployments implement this in their DNS servers. Besides, removing the check in the demo application may confuse users that are not aware of this, which would get them a non-working setup. As such, I'd either keep the check we had in the demo page, forcing users to provide a proxy (developers can always skip it in their implementations), or display a bootbox alert explaining this in order to allow users to choose (e.g., "You're not providing a proxy, this will cause/expect this, proceed?").

I can take care of this if you restore the JavaScript code to what it was before.

**Comment by saghul** [comment]
@lminiero fair enough :-) I removed the JS part.

**Comment by lminiero** [comment]
Thanks! I'll merge the patch right away.
At the moment I can't work on the dialog in JavaScript, but plan to do so as soon as I get back to the lab tomorrow in the morning.

**Comment by saghul** [comment]
> Thanks! I'll merge the patch right away.
> At the moment I can't work on the dialog in JavaScript, but plan to do so as soon as I get back to the lab tomorrow in the morning.

That would be great!

**Comment by lminiero** [comment]
Just modified the web page as we discussed, let me know if that works for you.

**Comment by saghul** [comment]
Works beautifully, thanks!

**Pull request merged**
