### PR TITLE
Webm pp fix

### PR DESCRIPTION
**Pull request by neilkinnish**

### CODE REVIEW

**Comment by lminiero** [comment]
?

**Comment by neilkinnish** [comment]
Sorry @lminiero it's the wrong PR, it's an experimental PR that got pushed by mistake. I'm hoping to push a real change at some point.

**Comment by lminiero** [comment]
Hopefully without the ton of code style changes... :wink:

**Comment by neilkinnish** [comment]
Haha, indeed. That is very much an experimental branch. :)

**Comment by neilkinnish** [comment]
@lminiero quick question, is there an easy way to get the frame count without loop through?

**Pull request closed without merging**
