### PR TITLE
Use editorconfig to help editors use the preferred style

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by lminiero** [comment]
You really did take my crazyness seriously :smile: 
I didn't know about this file, that's interesting!

**Comment by saghul** [comment]
I've been neglecting to try this stuff for a while, I guess today was a day as good as any :-) It does help, now my editor (The One True Editor, in case you were wondering) automagically configures to match the project style :-)

On a more serious note: I prefer indenting with spaces, but I prefer consistency above any of my style choices, so if the project author (you) chose tabs, so be it!

**Comment by lminiero** [comment]
How many spaces? Just so that I can match you to one of the profiles from that Perl forum...

**Comment by saghul** [comment]
4 spaces!

**Comment by lminiero** [comment]
Spiffy!

**Pull request merged**
