### PR TITLE
Bugfix/cpu usage based on v0.8.2

### PR DESCRIPTION
**Pull request by sjkummer**
avoid calling nice_agent_attach_recv() with a NULL callback, see https://gitlab.freedesktop.org/libnice/libnice/issues/14

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! I'm wondering if this warrants some new check in `janus_ice_cb_nice_recv`, though, as the main reason we set that callback to `NULL` is make sure we don't pass any media to plugins when we want to hang up the PeerConnection. Keeping the callback as it is will let libnice keep on telling about incoming packets, which means `incoming_rtp` may still occur after `hangup_media`, unless we have other checks to block media even when we're told about it.

**Comment by sjkummer** [comment]
Hm, we could use `nice_agent_remove_stream()` as Olivier Crête suggested (but I didn't test that yet) or implement an additional check in the callback function. What would you prefer?

**Comment by lminiero** [comment]
I think the additional check is the safest approach, especially since you tested this approach already. One more thing I'm wondering, though, is related to a comment I made on the original issue: https://github.com/meetecho/janus-gateway/issues/2015#issuecomment-605130186
If this only happens when calls fail, then it may be enough to only set the callback if the gathering works, while at the moment we always set it and then remove it when hanging up: unless the failures you were experiencing were not in `nice_agent_gather_candidates` but somewhere else?

**Comment by sjkummer** [comment]
Okay, I've updated the PR with an additional check.

Regarding gathering: In my logs I don't see `Error gathering candidates` ...

**Comment by lminiero** [comment]
Thanks! I'll make a couple of quick tests myself later and then merge :+1:

**Comment by lminiero** [comment]
Looks good, merging :+1:

**Comment by sjkummer** [comment]
Great, thanks 🙂

**Comment by lminiero** [comment]
@sjkummer did you manage to replicate the issue fairly easily, before this fix? If so, any chance you can capture a full libnice log (it should be enough to enable it in `janus.jcfg`) of when the problem happens, and share it with the libnice developers here? https://gitlab.freedesktop.org/libnice/libnice/-/issues/107
Thanks!

**Pull request merged**
