### PR TITLE
Add type definitions for the Janus Javascript API

### PR DESCRIPTION
**Pull request by eliasmeire**
This PR adds type definitions so that JS API users can have better tooling when working with the Janus Javascript API. (Typechecking, autocomplete etc.)

The definitions are not complete by any means but they are a great start, they helped me a lot when developing an app with Janus 👍

### CODE REVIEW

**Comment by GaijinKa** [comment]
LGTM

**Comment by lminiero** [comment]
Since our resident JS expert @GaijinKa gave the green light (it's pretty much Chinese to me instead!), that's fine for me as well!

@eliasmeire before I can merge, can you sign our [CLA](https://cla.conf.meetecho.com/janus/)? You'll need to authenticate via Github, and then fill in a form at the end of the page. Thanks!

**Comment by eliasmeire** [comment]
Hi thanks for having a look, I signed the CLA :).

**Comment by eliasmeire** [comment]
Sort of related to this PR, I was wondering if you guys would consider publishing janus.js as an npm package. It would really improve ease-of-use :). I know there was discussion on this in #793 and #552. If it changes anything I'm prepared to contribute, I think it would only require very minor changes.

**Comment by lminiero** [comment]
> Hi thanks for having a look, I signed the CLA :).

Thanks, merging then! :+1: 

> Sort of related to this PR, I was wondering if you guys would consider publishing janus.js as an npm package. It would really improve ease-of-use :). I know there was discussion on this in #793 and #552. If it changes anything I'm prepared to contribute, I think it would only require very minor changes.

No, we're not planning to do that. Publishing it would mean maintaining it, and to be very honest I have zero intention of doing that.

**Pull request merged**
