### PR TITLE
Modernize Janus

### PR DESCRIPTION
**Pull request by ibc**
Yeah modernize Janus.

### CODE REVIEW

**Comment by lminiero** [comment]
These are way too many changes for you to having made them manually! :D

**Comment by mirkobrankovic** [comment]
Seems legit to me ;)

**Comment by dwoz** [comment]
If it were not for all the missing context after this patch is applied I'd be all for it. Maybe modify the regex to not include the entire line. :|

**Comment by lminiero** [comment]
Since the future is too far away and this isn't Stargate, I'll have to reject this PR...

**Comment by ibc** [comment]
braveheart_3 2

**Pull request closed without merging**
