### PR TITLE
Add newline for SIP headers that are overflown in length

### PR DESCRIPTION
**Pull request by zayim**
Before this PR, if some header (key+value) is overflown (longer than 256 chars), it would result in it being truncated, but no newline was added, so it would result in next header actually being written on same line as overflown one, hence it was not interpreted as separate header on SIP level.

This PR makes sure that newline is added always, even if header (key+value) is longer than 256 chars.

### CODE REVIEW

**Comment by lminiero** [comment]
I'm not sure I understand why this should work. If the original string fills the string already, trying to append `\r\n` with `janus_strlcat` after that would still result in truncation and those two characters not being added. Am I missing something?

**Comment by zayim** [comment]
that might be true if we overflow entire `custom_headers` string, I was solving the case when we overflow one single header that is being written in `h` string.

I can add handling of the case when entire `custom_headers` string is overflown, make sure that we always have newline at the end of it

**Comment by lminiero** [comment]
I think that might help, thanks!

**Comment by zayim** [comment]
When you have time, check this again, it is now guaranteed that `custom_headers` will also end with `\r\n`, even if it is overflown.

**Comment by lminiero** [comment]
Hi @zayim, apologies for this very late reply, but I've been abroad the past few weeks and have just come back to work. I'll review the changes later today and let you know, thanks!

**Comment by lminiero** [comment]
Sorry again for the late review, was sidetracked by other activities... merging, thanks! I'll backport this to `0.x` too, since it's an easy patch to apply.

**Pull request merged**
