### PR TITLE
sipre: update sipreg_register to re 0.5.7

### PR DESCRIPTION
**Pull request by alfredh**
This patch updates the sipre plugin to use the latest api of libre 0.5.7

in 0.5.7 the sipreg api was changed:

https://github.com/creytiv/re/releases/tag/v0.5.7

please merge to master.

### CODE REVIEW

**Comment by lminiero** [comment]
Won't this break compatibility with previous releases, though? I think it might be better to make this conditional to the version detected in configure. I'll check if that can be done easily.

**Comment by alfredh** [comment]
yes it will break compatibility with older versions of libre.

my apologies for that :)

Alfred

**Comment by lminiero** [comment]
@alfredh I noticed your headers don't include any versioning info as a define of some sort. Any chance this could be added in the future? It would allow for a much easier management of change in the APIs directly in the code with macros, rather than having to resort on configure.ac tweaks to detect exact versions and add defines there.

**Comment by lminiero** [comment]
For the time being, handled this as a configure check. Thansk for the heads up!

**Comment by alfredh** [comment]
great idea, we can add version info in the header files ..

Thanks for merging

**Pull request closed without merging**
