### PR TITLE
Added support for time reset in the rtp payload

### PR DESCRIPTION
**Pull request by kris-lab**
Part of https://github.com/cargomedia/janus-gateway-rtpbroadcast/issues/62

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks for working on this! Did you notice problems when post-processing media without this fix? IIRC we had code in place to handle these resets, but it's been some time since last time I've worked on the post processor so I may be wrong.

As a side note, have you signed our [CLA](https://cla.conf.meetecho.com/janus/) already?

**Comment by lminiero** [comment]
Nevermind my question, just read your explaination on the referenced issue and your fix makes sense. I'll review ASAP and come with feedback, thanks!

**Comment by kris-lab** [comment]
@lminiero yes, I have experienced small issue with conversion of large RTP dumps. I have noticed that if there is time reset on the RTP payload then conversion cannot be finished. I can see there is implementation to cover that case but in our scenario it looks like looping back for finding previous packet is not possible. That means for each `next` packet in the list the `while` loop always goes to the beginning.

I believe my workaround is not perfect. I would rather try to combine this implementation with  `reset` https://github.com/meetecho/janus-gateway/blob/master/postprocessing/janus-pp-rec.c#L243 which is already there. 

wdyt?

**Comment by lminiero** [comment]
I do remember working on that a long time ago, as it was happening for some of our recordings that were longer than others, and it seemed to do the trick: the internal timestamp we use for ordering is a 64 bit integer that we can do our ordering on then.

Not sure what's causing it to fail in your case. Looking at the code, I thought we were also keeping track of the number of resets there had been (that's what I remembered), but apparently that's not the case, and so we're only handling a pre-reset and post-reset case, meaning that if there is a second reset along the road things may break there. I guess we might have disregarded the case as unlikely (IIRC you need more than 13 hours for a reset, starting at 0). If so, and that's what's happening to you (loop at the second reset), then just keeping track of the number of resets and using that in conjunction with the reset calculator we have may do the trick.

**Comment by lminiero** [comment]
PS: do you have a mjr file to share that I can use to test this, and to check how I can fix it with my idea on the resets counter approach?

**Comment by kris-lab** [comment]
I do have it but it is 36GB! Will check can I easily share it with you. The problem currently appears ~28GB so testing is very painful as you have to read this data every time to build the list of packets.

**Comment by kris-lab** [comment]
And yes, I agree with your tips and approach. Will try to have a look asap.

@njam wdyt about file sharing?

**Comment by kris-lab** [comment]
I am uploading this file into the google drive. Could you share you e-mail so I will send you invite. thx

**Comment by lminiero** [comment]
That's huge! :fearful: If so, this seems to confirm it might indeed be a double reset that's causing the issue: anything that lasts between 13 and 26 hours (depending on what the initial timestamp was) may have a second reset in it, and so causing the issue. In that case, while processing you should actually see a first successfull timestamp reset:
https://github.com/meetecho/janus-gateway/blob/master/postprocessing/janus-pp-rec.c#L244
and then a problematic one later on.

That said, with such a huge file, sharing it is out of the question I guess... I'll try to come up with a patch to handle the resets counter shortly (probably tomorrow) so that you can test it yourself.

**Comment by lminiero** [comment]
> I am uploading this file into the google drive. Could you share you e-mail so I will send you invite. thx

Nevermind, it would take forever to download, I'll work blind and try to prepare a PR ASAP :wink:

**Comment by kris-lab** [comment]
Ok then! I am stopping my upload :smile: and also fyi we do have files up to 120GB with tens of hours of streaming. I guess the reset can occur for multiple time there.

Many thanks for taking care of it. I will test your patch asap.

**Comment by lminiero** [comment]
@kris-lab @njam can you have a look at the new PR I created? It should address the multiple timestamp resets we discussed yesterday.

I don't have access to a recording that actually includes them, so I can't be sure it works as expected: I did a simple test by generating a fake mjr recording that contained a couple of resets, and it seemed to detect them correctly and set the internal 64 bit timestamp value correctly, but, again, not sure if this actually solves the issue. Besides, the code is a bit hacky right now and with a lot of LOG_WARN here and there to highlight what I was interested in. Feedback welcome!

**Comment by kris-lab** [comment]
This issues has been solved in #472 

Closing. Please reopen if needed.

**Pull request closed without merging**
