### PR TITLE
sip: add ability to customize the display name

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks, looks fine to me!
Can you just fix the indentation, though? I noticed some of the lines have spaces instead of tabs.

**Comment by saghul** [comment]
Doh, I thought I had the damn plugin installed. Fixup coming up!

**Comment by saghul** [comment]
I think I got them all. Can you PTAL?

**Comment by lminiero** [comment]
Can I [Postgraduate Training Authorization Letter](http://www.ecfmg.org/eras/applicants-documents-pta.html)? Of course! :smile: 
Jokes apart, thanks, it looks good now, merging!

**Comment by saghul** [comment]
Oh, I meant "Please Take A Look", of course :-) Thanks!

**Pull request merged**
