### PR TITLE
Prevent race conditions on socket close in SIP and NoSIP plugins

### PR DESCRIPTION
**Pull request by lminiero**
We noticed that in some cases, in misconfigured instances of Janus with high socket contention and high traffic, a race condition could happen where a socket would be closed twice. This is an issue whenever the second time we close a socket it was actually assigned to someone else in the meanwhile: if the socket was used internally by `getifaddrs`, for instance, this could cause that method to lock and never return, and since in Janus that call may be on a critical path, deadlock relevant functionality.

This PR tries to fix this behaviour in SIP and NoSIP plugins, as the SIP plugin is where we noticed this happening, and the NoSIP plugin borrows a lot of the same code. The Streaming plugin doesn't seem to be affected instead, as only a mountpoint thread messes with the struct file descriptor values.

Feedback welcome, especially if you use those plugins a lot in production.

### CODE REVIEW

**Comment by bhakimi** [comment]
thanks a ton!!!! @lminiero

**Comment by lminiero** [comment]
@ihusejnovic since I know you guys use the SIP plugin a lot, we'd welcome feedback on this PR: we'd like to merge it soon. Thx!

**Comment by ihusejnovic** [comment]
Sure, we will test it. Can you just sync this branch with master?

**Comment by ihusejnovic** [comment]
We are using this branch last few days and we didn't notice any issues so far.

**Comment by lminiero** [comment]
Merging.

**Pull request merged**
