### PR TITLE
Allow for a separate authentication username.

### PR DESCRIPTION
**Pull request by tuijldert**
Relates to:
https://github.com/meetecho/janus-gateway/issues/352

Please review and apply.

Thanks,
Tom.

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks, I'll look into it tomorrow. Please use tabs instead of spaces for indenting, though: we have an .editorconfig file that can help fix this automatically.

As a side note, have you signed our [CLA](https://cla.conf.meetecho.com/janus/)? As explained [here](https://github.com/meetecho/janus-gateway/blob/master/CONTRIBUTING.md) we require this for all contributions.

**Comment by tuijldert** [comment]
Apologies for the mess, was fooling around with codelite.
Obviously haven't found the editor settings yet :)

CLA: done.

**Comment by lminiero** [comment]
Thanks!

The .editorconfig file is here: https://github.com/meetecho/janus-gateway/blob/master/.editorconfig
It's something I was not aware of and that @saghul notified me about: if your editor supports the format (many do) it can help you automatically use the coding guidelines according to the project. Anyway, it's just a matter of using tabs for indentation mostly, we're not that picky for the rest :smile:

**Comment by tuijldert** [comment]
I back-patched this to our deployed version and ran tests:
Ok: old behaviour (no 'authuser' given, username is also auth username)
Ok: new parameter (authuser given, same as username)
Ok: new behaviour (authuser given, differs from username).

**Comment by lminiero** [comment]
Thanks! I'll give a look this afternoon and merge in case everything works fine for me as well.

**Comment by lminiero** [comment]
I don't see any new commit though, have you not pushed it yet?

**Comment by tuijldert** [comment]
?? I forked the latest, committed on that fork and used that to create the pull-request (I think) ?
So there must be a commit.

The back-patch was just for me to test so no commit there. Inclusion in only the latest version is OK with me.

Or are you referring to the tab/indent-stuff? (I sort of assumed you'd incorporate that on the fly)

**Comment by lminiero** [comment]
Yep, I was referring to the indentation stuff, that's why I was looking for a further commit. No problem, I can fix that after the merge.

**Comment by lminiero** [comment]
This line is wrong:
https://github.com/tuijldert/janus-gateway/blob/master/plugins/janus_sip.c#L1146

    authuser_text = json_string_value(authuser_text);

should be

    authuser_text = json_string_value(authuser);

as ```json_string_value``` expects the ```json_t``` object you just retrieved, while you're passing it a NULL char * pointer. Are you sure this was working for you? As it was, ```authuser_text``` was always NULL.

**Comment by tuijldert** [comment]
Whoops, sorry, typo!

Back-patched it correctly in the deployed version :( so you're absolutely right... and so the tests succeeded....

Apologies for the extra hassle I caused you.

**Comment by lminiero** [comment]
Not sure what the back-patching you refer to is about, I still see the same line in the "Files changed" tab and the related commit. If the patch is now different, can you prepare a new pull request with the amended version? Thanks!

**Comment by tuijldert** [comment]
Sorry, not too fluent in github handling...

I think the last commit I uploaded is now part of this PR, can you check please?

In it, I fixed the indenting and the json retrieval line. Should be clean and Ok now.

I applied the patch manually to my deployed gateway version in order to be able to test it, that was the back-patch I was referring to (and in which I unwittingly did things right).

Anyway hope all is ok now.

**Comment by lminiero** [comment]
Yes, that looks like it, thanks! I'll give it a quick go and in case merge right away, thanks for taking time to work on this effort!

**Pull request merged**
