### PR TITLE
BUGFIX : opus fill silence packet

### PR DESCRIPTION
**Pull request by jing3018**

### CODE REVIEW

**Comment by lminiero** [comment]
What issue did you notice that needed this fix? It seemed to be working fine for us.

**Comment by jing3018** [comment]
1. the granulepos is not monotonous，the value in the silence packet is big the the follow valid packet. 
```
in silence packet : pos = tmp->seq-list->seq+steps*65536+i+1;
but when write packet tmp
in tmp packet  :   tmp->seq-list->seq+steps*65536
```

2. when lost `N` packet,  writen `N+1` silence packet
```
tmp->seq-tmp->prev->seq  - 0     == N + 1
tmp->seq-tmp->prev->seq - 1 -0  == N
```

**Comment by lminiero** [comment]
Thanks for the clarification! I'll look into this when I get back to the office, as I'm currently in Japan for work and so have only limited time to look into code and things. Ping me if I forget to do that! :smile:

**Comment by jing3018** [comment]
@lminiero ， have you review this pull request?

**Comment by lminiero** [comment]
@jing3018 I've returned to work this morning, I'll look into this in the next few hours. Thanks for the reminder!

**Comment by lminiero** [comment]
I was able to verify this, thanks for fixing it. I also noticed that we're doing an error writing twice the size of opus_silence (it should just be ```sizeof(opus_silence)```), I'll commit that after I merge this.

**Pull request merged**
