### PR TITLE
fix Bootstrap issue on mobile that requires a double tap on Watch button

### PR DESCRIPTION
**Pull request by willamowius**
fixing issue #2220

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! I'll have a look at the changes later and review :+1:

**Comment by lminiero** [comment]
I'm afraid this change breaks the UI. First of all, it starts with one of the streams already selected, rather than showing the placeholder/guidance we have now. Besides, the look&feel is broken too, because the form is not using the Bootstrap CSS. As such, I don't think this can be merged as it is.

**Comment by willamowius** [comment]
I'd consider not having an invalid choice that always produces an error in the list as a feature, not a bug, but if you prefer it that way, I have added one.

I don't see how the new version is not using Bootstrap CSS. Bootstrap is about styling HTML which this version does. That the old version was mimicking an HTML Select with with other elements is not a feature you should want to keep, especially since it didn't work on any mobile browser (neither Android nor iOS).

**Comment by lminiero** [comment]
> I'd consider not having an invalid choice that always produces an error in the list as a feature, not a bug, but if you prefer it that way, I have added one.

It is a feature to me. If people see a title right away, they might thing that's all there is. An "invalid choice", as you call it (I call it a guide) tells them to check whats available. We have the same in the SIP plugin, where we DO want people to see the different ways they can register. Our demos may be ugly as hell, but we did give some thought to them, so please don't change existing behaviours.

> I don't see how the new version is not using Bootstrap CSS. Bootstrap is about styling HTML which this version does. That the old version was mimicking an HTML Select with with other elements is not a feature you should want to keep, especially since it didn't work on any mobile browser (neither Android nor iOS).

Well, it isn't. This is how it looks now:

select1

This is how it looks after your fix:

select2

Again, I'd never call our demos sleek or pretty, not at all, but I definitely don't want them to look even uglier than they already are. Bootstrap styling is definitely not happening for the new `select` you added, so that should be fixed before I can merge this.

**Comment by lminiero** [comment]
Notice how the "invalid choice" doesn't appear in the select, because it's really not supposed to be part of the choices. This is how Bootstrap styles drop-down menus, and why we used that approach for the selector in here as well.

**Comment by willamowius** [comment]
Then I'm afraid you need to find somebody else to fix your style of select on mobile. I didn't see a way to do it and not having mobile working isn't an option for me.

**Comment by lminiero** [comment]
No problem, we have the issue open, so either us or someone else will hopefully find time to look into it sooner or later. Thanks anyway!

**Pull request closed without merging**
