### PR TITLE
Batch configure support for streaming plugin

### PR DESCRIPTION
**Pull request by petarminchev**
Supporting a streams array param to configure multiple mids in one batch request.

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @petarminchev! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Review by lminiero — COMMENTED** [review]
It seems ok, but I haven't tested it yet: I only added a couple of editorial comments. What's definitely missing, though, is documentation: the `streams` array for "configure" is not documented in the doxygen part of the code, which we did in #2986.

I just noticed though that the "configure" request in the Streaming plugin seems to only do something on RTP (and RTSP) mountpoints, though, which means that the file-based mountpoints were never impacted. This is a note to self, since it means I'll probably have to add something for them too (at the very least to tweak the `send` property, for instance).

**Comment by lminiero** [comment]
@petarminchev thanks! I'll make a couple of tests later today, and I've launched the CI checks on the branch too.
I noticed you haven't signed the CLA though? Please do that at your earliest convenience, since without that step I can't merge this.

**Comment by lminiero** [comment]
It must be signed by you: you're the author of the patch.

**Comment by lminiero** [comment]
Sorry for the lack of feedback! I plan to make a couple of tests later today and merge in case it's fine :+1:

**Comment by lminiero** [comment]
Made a few tests with a multistream mountpoint with multiple simulcast video streams, and it does seem to work as expected :+1:  I vedified that a "legacy" configure request with no mid seems to be enforced on all streams, which means it is backwards compatible too. Merging then, thanks again!

**Pull request merged**
