### PR TITLE
Fix libnice build command

### PR DESCRIPTION
**Pull request by kenju**
as described in the README.md of libnice,
the build command using meson/ninja has been changed

https://gitlab.freedesktop.org/libnice/libnice

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @kenju! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Comment by atoppi** [comment]
Hi @kenju ,
I have tested the current instructions with the latest libnice `master` and it works as expected, nothing changed in the build process as far I can tell.

I'm afraid we can not accept this change since your patch:

- renames the libnice build directory from `build` to `buildir` (pointless change)
- removes the recommended libnice version (`0.1.19`), switching to `master`
- removes the destination prefix for the built library (`/usr`)

**Comment by lminiero** [comment]
> removes the recommended libnice version (`0.1.19`), switching to `master`

Actually this is incorrect, this patch added checking out 0.1.19 (which is indeed suggested). But on the rest I agree, I don't see any relevant change, since we were already using meson and ninja in the README.

**Comment by atoppi** [comment]
> removes the recommended libnice version (0.1.19), switching to master

Sorry for the mistake, of course you're doing the opposite! Still the whole patch is not acceptable because the build process is working as it is.

**Pull request closed without merging**
