### PR TITLE
Fixes on JavaScript code snippets

### PR DESCRIPTION
**Pull request by 0xdw**
- JavaScript Code cleanup
- Fixes on JavaScript code snippets

### CODE REVIEW

**Comment by lminiero** [comment]
This seem all whitespace fixes, which IMO are irrelevant. Please only submit fixes to code that would be broken if copied.

**Comment by 0xdw** [comment]
> These seem all whitespace fixes, which IMO are irrelevant. Please only submit fixes to code that would be broken if copied.

Sure. More of them are whitespace fixes. Only a couple of code snippet fixes.

**Comment by lminiero** [comment]
> Sure. More of them are whitespace fixes. Only a couple of code snippet fixes.

Yes, and to be honest I'm not interested in whitespace fixes: I'm not going to merge those. Please limit the patch to code snippet fixes instead.

**Comment by 0xdw** [comment]
> > Sure. More of them are whitespace fixes. Only a couple of code snippet fixes.
> 
> Yes, and to be honest I'm not interested in whitespace fixes: I'm not going to merge those. Please limit the patch to code snippet fixes instead.

Sure. I'll commit only code fixes

**Comment by 0xdw** [comment]
OK, I reversed the whitespace fixes and left js snippet fixes.

**Comment by lminiero** [comment]
Thanks, merging :+1:

**Pull request merged**
