### PR TITLE
recordplay: allow client to specify filename (optional)

### PR DESCRIPTION
**Pull request by davibe**
I found this useful for my integration. See if you care to merge it.

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks for this! It's definitely helpful, as we have similar features in the streaming and videoroom plugins.

I'm not convinced by the ```g_stpcpy```, though, especially considering the buffer is limited and this can lead to overflows and crashes. Could you modify the code to use g_snprintf instead as the rest of the code does?

**Comment by davibe** [comment]
sure

**Comment by davibe** [comment]
You forgot about this :)

**Comment by lminiero** [comment]
Apologies, github didn't notify me about the new revision... merging now, thanks!

**Pull request merged**
