### PR TITLE
Repaired link to issue templates

### PR DESCRIPTION
**Pull request by tacerus**

### CODE REVIEW

**Comment by lminiero** [comment]
Good catch, thanks: this changed when we started using the issue template generator in GitHub itself, and I didn't remember we had a link in the README. Merging :+1:

**Comment by lminiero** [comment]
Actually, looks like we should link to this file instead:

https://github.com/meetecho/janus-gateway/blob/master/.github/CONTRIBUTING.md

since the issue template is now a folder with little human readable info. I'll change this shortly.

**Comment by tacerus** [comment]
That'd make more sense indeed. I can change it.

**Comment by tacerus** [comment]
Ah, you already did. Very nice! :)

**Pull request merged**
