### PR TITLE
Ability to configure virtual host, username, and password for RabbitMQ

### PR DESCRIPTION
**Pull request by hasbean**
Nothing huge, just a requirement I had and thought I'd push the changes.

### CODE REVIEW

**Comment by lminiero** [comment]
Whoops, sorry, I saw this, couldn't comment right away and then completely forgot about this! I'll look into it today and come back with comments (if any) ASAP. Thanks!

**Comment by lminiero** [comment]
A couple of quick comments:

1. vhost, username and password should be freed in case something goes wrong, as we do for other parsed config values here, https://github.com/meetecho/janus-gateway/blob/master/transports/janus_rabbitmq.c#L343
2. why are host, username and password only parsed and used when logging in for the Janus API queues? the new RabbitMQ module can be used for the Admin API as well.

**Comment by hasbean** [comment]
1. Whoops, didn't catch that!  I'll add them.

2. That was the plan originally, but the Janus API and Admin API use the same connection, not two separate connections.  These parameters can only be used in amqp_login which is only called once in the code.

**Comment by lminiero** [comment]
> That was the plan originally, but the Janus API and Admin API use the same connection, not two separate connections. These parameters can only be used in amqp_login which is only called once in the code.

Good catch: I thought we actually allowed for different RabbitMQ servers to be used for the two of them, but that's indeed not the case, we just use different queues. I'm wondering now if it makes sense to have such an option... anyway, not relevant to this patch, so please disregard that comment then!

**Comment by lminiero** [comment]
PS: partly related to the point before, though, the ```vhost```, ```username``` and ```password``` part are only parsed if ```enable=yes``` in ```[general]```, that is if the Janus API over RabbitMQ is enabled. It might happen that the Janus API usage for RabbitMQ is disabled while the Admin API is enabled, which would still lead to a login, but with NULL values for ```vhost```, ```username``` and ```password```.

As such, I'd put reading those values from the config outside of the ```enable=yes``` if (maybe before that?), so that it's actually shared for both APIs.

**Comment by hasbean** [comment]
Half awake, but it should be good now.

**Comment by hasbean** [comment]
I'm not really sure what's with the inconsistent indentation.  It looked fine on Xcode but not here.

**Comment by lminiero** [comment]
Thanks (especially for doing this almost asleep eheh), I'll give it a quick test after lunch and in case everything's fine I'll merge it right away.

**Comment by lminiero** [comment]
Merging, thanks!

**Pull request merged**
