### PR TITLE
Documented `display_name` parameter in SIP plugin's `register` request.

### PR DESCRIPTION
**Pull request by zayim**

### CODE REVIEW

**Comment by lminiero** [comment]
Good catch, thanks for spotting this! Can you fill in the form for our [CLA](https://cla.conf.meetecho.com/janus/) and sign it so that we can merge?

**Comment by zayim** [comment]
Thanks! I updated PR with description for 2 more fields, and signed CLA.

**Comment by lminiero** [comment]
Looks good, thanks! Merging then :+1:

**Comment by lminiero** [comment]
I updated the online documentation as well: https://janus.conf.meetecho.com/docs/sipsofia

**Pull request merged**
