### PR TITLE
Check media resources and handle them

### PR DESCRIPTION
**Pull request by leonuh**
Videomcu doesn't work if you have only audio input

### CODE REVIEW

**Comment by leonuh** [comment]
I found something regarding to this issue  - https://github.com/GoogleChrome/webrtc/commit/c6b0c13c08c2de503fd1457d4f31e5f3bc9c4240 - Maybe the adapter.js needs an update too.

**Comment by lminiero** [comment]
Thanks for the heads-up. That adapter also removes some checks that were there before, though, assuming some versions are not around anymore. Not sure how certain that can be. I'll see if I can prepare a new adapter.js that is more comprehensive.

**Comment by lminiero** [comment]
It seems to be working fine with all browsers this way, but apparently there are a few issues with a couple of plugins right now and the way they handle the resulting SDP, which causes Firefox Nightly to rightly complain. I'll fix those in the next few days and then merge your contribution.

**Comment by lminiero** [comment]
Merging, a followup commut to fix things up will follow.

**Comment by amki** [comment]
This leads to a bug with Firefox:

TypeError: MediaStreamTrack.getSources is not a function janus.js:1378:5

MediaStreamTreack.getSources is not (yet?) implemented in Firefox.

**Comment by lminiero** [comment]
> MediaStreamTreack.getSources is not (yet?) implemented in Firefox.

You're probably not using the latest adapter.js we have in the repo.

**Pull request merged**
