### PR TITLE
Add PHPClass to Resources

### PR DESCRIPTION
**Pull request by mvnrsa**

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! Can you sign our [CLA](https://cla.conf.meetecho.com/janus/) so I can merge right away?

**Comment by lminiero** [comment]
Thanks again, merging!

**Comment by lminiero** [comment]
https://janus.conf.meetecho.com/docs/resources

**Comment by mvnrsa** [comment]
Tx!

Marnus van Niekerk

On 06 Sep 2017 18:32, "Lorenzo Miniero" <notifications@github.com> wrote:

https://janus.conf.meetecho.com/docs/resources

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/meetecho/janus-gateway/pull/994#issuecomment-327540601>,
or mute the thread

**Pull request merged**
