### PR TITLE
ice: check if rtcp_ctx is NULL before use

### PR DESCRIPTION
**Pull request by tmatth**
Every other use of rtcp_ctx has an equivalent check.

Refs #1600.

### CODE REVIEW

**Comment by tmatth** [comment]
Maybe wait until an adequate backtrace is provided to make sure that this is really a case of `rtcp_ctx` being NULL.

**Comment by lminiero** [comment]
Thanks! We don't have that check in master either, though... anyway, in unified-plan it might indeed be happening because of how more often renegotiations can happen. Let's wait for feedback from @amnonbb  and maybe for him to check if this patch fixes it for him.

**Comment by tmatth** [comment]
> Thanks! We don't have that check in master either, though... anyway, in unified-plan it might indeed be happening because of how more often renegotiations can happen. Let's wait for feedback from @amnonbb and maybe for him to check if this patch fixes it for him.

If @amnonbb confirms it, I could make the equivalent patch in master and you could merge it into this branch (if that makes more sense).

**Comment by amnonbb** [comment]
I puted this fix on committed day. Until now issue did not back, but i would wait some weeks. I don't know how to reproduce it and when exactly it was happen.

**Comment by lminiero** [comment]
I'll merge then. I'll apply a similar fix to master when I have some time. Kudos to @tmatth for promptly taking care of this and other issues lately!

**Comment by lminiero** [comment]
Applied to master as well here: https://github.com/meetecho/janus-gateway/commit/b8d21988216d676d55a8bab70277332255fbcf1a

**Pull request merged**
