### PR TITLE
Add package.json

### PR DESCRIPTION
**Pull request by medialwerk**

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! Before I can merge, could you sign our CLA at the bottom of [this page](https://cla.conf.meetecho.com/janus/)?

**Comment by medialwerk** [comment]
Done! - Thanks too :-)

**Comment by Tom-Tom** [comment]
Can we add `janus.nojquery.js` ?

**Comment by lminiero** [comment]
Cool, thanks! Merging then.

**Comment by medialwerk** [comment]
I missed that file, i added it :-)

**Pull request merged**
