### PR TITLE
Optional Authorization header in first REGISTER

### PR DESCRIPTION
**Pull request by lminiero**
This patch tries to address issue #450 by adding two optional attributes in a ```register``` request:

1. ```authheader```, if ```true```, forces an Authorization header in the first REGISTER;
2. ```real``` is a string that MUST be specified if ```authheader``` is ```true```, as without feedback from the server (e.g., 401) there's no way for the plugin to figure out what the realm is going to be by itself.

An example of how to use this in the demo:

    sipcall.send({message: {request: "register", username: "sip:lminiero@example.com", secret: "password", authheader: true, realm: "example.com"}});

which would result in this header being added to the REGISTER:

    Authorization: Digest username="lminiero", realm="example.com", nonce="", response="", uri="sip:example.com"

This shouldn't break anything, especially since it's optional, but I'm making this a PR nevertheless, also to make sure this actually solves @hoangtuansu's use case in a programmatic way.

### CODE REVIEW

**Comment by saghul** [comment]
Can't we just ignore IMS altogether? I'm not kidding here.

**Comment by lminiero** [comment]
I don't care about it either (I'm surprised there's people that still do!), but if there's people interested and the only needed fix to get it working is really tiny then I guess there's no harm. I'd of course refuse any major change that tried to address IMS: that may belong to a different plugin entirely, if any.

**Comment by saghul** [comment]
That's my fear, that this patch will open the can of worms :-)

**Comment by lminiero** [comment]
No need to worry, our IMS tolerance ends here! :smile:

**Comment by hoangtuansu** [comment]
Hello,
I'm very sorry for my false report. I've checked again and see that the error is caused due to my mistake. It's because of the value of "authuser", no matter whether or not the authorization header is present in first REGISTER message. 

In case the "authuser" is not specified, the GW uses username (i.e. bob) by default. In OpenIMSCore, this leads to the error "403 Forbidden : HSS user unknown". So I modified client's code adding an additional field (i.e. "authuser" : "bob@open-ims.test") and it works.

Iminiero, could you please discard this change? I'm very sorry for this inconvenience.

**Comment by lminiero** [comment]
@hoangtuansu do you mean that the version of the plugin in master works with OpenIMSCore already, without the need for the header to be present in the first REGISTER too?

**Comment by hoangtuansu** [comment]
Yes, it works already.

**Comment by lminiero** [comment]
Ok, tnx, closing the pull request then.

**Pull request closed without merging**
