### PR TITLE
Remove duplicated code.

### PR DESCRIPTION
**Pull request by fancycode**
Here is a PR that moves some duplicated code into a separate function.

Are you generally interested in similar PRs that improve the readability of the code?

### CODE REVIEW

**Comment by lminiero** [comment]
Mh, this is code I changed considerably in #1231, so I'd ask you to please base these optimizations on that branch rather than master, since I plan to merge it soon. Thx!

**Comment by lminiero** [comment]
In general, patches that avoid duplicates are welcome, as those tend to make mistakes easier. I'm only against when improving the readability results in making the code needlessly more complex than it was before.

**Comment by fancycode** [comment]
Ok, so I'll wait for #1231 to land and will rebase then.

**Comment by lminiero** [comment]
Merged the code, so you can rebase now... sorry if this introduced a conflict, and thanks again for your help!

**Comment by fancycode** [comment]
Rebased.

**Comment by lminiero** [comment]
Looks good, thx, merging!

**Pull request merged**
