### PR TITLE
Pointer assignment is not defined to be atomic, so participant recorder…

### PR DESCRIPTION
**Pull request by areuthere**
…s must be guarded by mutex

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @areuthere! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Comment by areuthere** [comment]
> Thanks for your contribution, @areuthere! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

Unable to sign CLA, some weird issue says "Un authorized" and throwing out

**Comment by areuthere** [comment]
image

**Comment by lminiero** [comment]
We'll have a look to see if something broke there.

**Comment by lminiero** [comment]
@areuthere please check again, it should work now.

**Comment by areuthere** [comment]
> @areuthere please check again, it should work now

@lminiero It worked. Thanks

**Comment by lminiero** [comment]
Sorry for the late feedback. This may not be needed, as internally `janus_recorder_save_frame` already uses a mutex for the recorder itself.

**Comment by lminiero** [comment]
Closing per comment above.

**Pull request closed without merging**
