### PR TITLE
Send a FIR to the new RTP forward publisher

### PR DESCRIPTION
**Pull request by amnonbb**

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! I guess this was indeed needed.

Can you remove the extra space before each of those lines? It's messing up the indentation.
Please also sign our [CLA](https://cla.conf.meetecho.com/janus/), as we require that for all contributions.

**Comment by amnonbb** [comment]
Done

**Comment by lminiero** [comment]
Thanks for the quick fix. Just looked into the patch a bit more and I think we just need a further check, that is whether the RTP forwarder actually involves video or not: as it is, this would send a FIR/PLI even for an audio only forwarder, which is probably not what we want.

Can you move that code in the ```if(video_handle > 0) {``` that is a few lines below, so that it only kicks in when we actually created a video handle?

**Comment by amnonbb** [comment]
i'll test it..

**Comment by amnonbb** [comment]
Thanks for review. I tested, it's work.
Worth to know that 1 from 20-30 switches may miss keyframe.
but it's may gstreamer pipeline problem.
Anyway without FIR request in gstreamer out it's look horrible on every switch.

**Comment by lminiero** [comment]
Thanks, merging!

**Pull request merged**
