### PR TITLE
fixed parse width/height from sps

### PR DESCRIPTION
**Pull request by PeterXu**
shown in code.

### CODE REVIEW

**Comment by lminiero** [comment]
Is this really needed? Can you elaborate on what it fixes? I never saw problems in extracting the correct resolution of a keyframe with the existing code, and I use the same code successfully in some live RTP servers as well (so not only postprocessing).

**Comment by lminiero** [comment]
@PeterXu ping :wink:

**Comment by PeterXu** [comment]
For some cases, frame_crop_bottom_offset or frame_crop_top_offset may not be 0.
In my testing, H264 640x360 from Chrome(version: 63) will not be processed correctly.

**Comment by lminiero** [comment]
Thanks for the clarification, I'll make some tests and check if it still works as expected in my other scenarios too. In the meanwhile, could you sign our CLA at the end of [this page](https://cla.conf.meetecho.com/janus/) so that I can merge after I've done my checks?

**Comment by PeterXu** [comment]
I have signed it and expect your checking.

**Comment by lminiero** [comment]
Looks like it's still working, merging then!

**Pull request merged**
