### PR TITLE
Fix deadlock when feed parameter is missing

### PR DESCRIPTION
**Pull request by apietrzak**
When feed parameter is not set videoroom plugin hangs up.

### CODE REVIEW

**Comment by lminiero** [comment]
Good catch, and thanks for the fix! Can you sign our [CLA](https://cla.conf.meetecho.com/janus/) so that I can merge this?

**Comment by lminiero** [comment]
@apietrzak ping :wink:

**Comment by apietrzak** [comment]
> @apietrzak ping 😉

Yeah, I know. If I receive all permissions I will inform you. It takes some time in our company. I think it should be done today.

**Comment by lminiero** [comment]
Got it, thanks for the feedback :+1:

**Comment by lminiero** [comment]
@apietrzak sorry to insist, but any news? I'm waiting for this to be merged (along with a couple of other things) to tag a new version. Thanks!

**Comment by apietrzak** [comment]
> @apietrzak sorry to insist, but any news? I'm waiting for this to be merged (along with a couple of other things) to tag a new version. Thanks!

I have had allmost all permissions. Because of coronavirus, our company is processing different request with higher priority. Sorry for inconvinience. I will update you when I receive any information.

**Comment by lminiero** [comment]
@apietrzak this is getting ridicolous now, though... either your company (which is apparently benefiting from Janus anyway) is ok with you signing the CLA, or it isn't. Sorry, but we can't hold on fixes because they take two weeks to read a document. If the CLA won't get signed soon, I'll close the issue and we'll fix it a different way.

**Comment by apietrzak** [comment]
> @apietrzak this is getting ridicolous now, though... either your company (which is apparently benefiting from Janus anyway) is ok with you signing the CLA, or it isn't. Sorry, but we can't hold on fixes because they take two weeks to read a document. If the CLA won't get signed soon, I'll close the issue and we'll fix it a different way.

Sorry for late response. Today it is going to be done. I will keep you inform.

**Comment by lminiero** [comment]
No need anymore. A more comprehensive patch including multiple locking fixes has been provided and merged. Thanks for the contribution anyway.

**Pull request closed without merging**
