### PR TITLE
Add display property on leave or unpublish event

### PR DESCRIPTION
**Pull request by amnonbb**
As title say. If it's not doing problem somewhere it's help to get display property in event as it's done in other places.

### CODE REVIEW

**Comment by lminiero** [comment]
Good catch: is that what you meant to do @amnonbb?

**Comment by amnonbb** [comment]
> Good catch: is that what you meant to do @amnonbb?

Yes. it is. Almost in all places we got display property except  kicked / unpublished / leaving

**Comment by amnonbb** [comment]
> Just to double check since it is not being mentioned: this is for the `kicked` / `unpublished` / `leaving` event emitted **to the event handlers**, so unrelated to the Janus API event.

Sorry, now i understood what you ask. Event handlers is where i used it and keep fork only for this change. But generally may be right to add it in Janus API event as well.

**Comment by lminiero** [comment]
@amnonbb looks good to me! Could you also update the documentation of the impacted events, though, to clarify there could be a `display` property too now?

**Review by oksy31 — APPROVED** [review]

**Comment by lminiero** [comment]
Thanks, merging! I'll consider if porting the same patch to 0.x as well.

**Pull request merged**
