### PR TITLE
Fix MacOS Install Instructions

### LINKED ISSUE #897: Mac OS Install Instructions Broken (libnice)
Homebrew recently (last month) removed support for installing formulae via the boneyard (see https://github.com/Homebrew/homebrew-boneyard/pull/314).

This was required in order to install libnice on OS X.

I haven't been able to get libnice to build without error from source and instructions I've found so far are quite out of date. Maybe someone else has an answer here so we can submit a PR to get this remedied.

### PR DESCRIPTION
**Pull request by joshdickson40**
Fixes #897.

`brew tap homebrew/boneyard` is now deprecated (and not working) so `libnice` must be installed manually.

See https://github.com/Homebrew/homebrew-boneyard/pull/314

### CODE REVIEW

**Comment by lminiero** [comment]
Not sure we want to suggest 1.1.14, as it may suffer from the problem described in #788. Apart from that, I'll leave to MacOS users to test and provide feedback before I merge, as I don't own one.

**Comment by joshdickson40** [comment]
Ah you're right, maybe 1.1.13 is the way to go. I am still having a hell of a time getting Janus to build on MacOS so maybe we can leave this open for a bit.

**Comment by lminiero** [comment]
@joshdickson40 did you manage to make any progress here?

**Comment by joshdickson40** [comment]
No, I've been tied up in some other stuff, sorry. I do intended to get back to this as well as the Firefox issue on the adapter.js ontrack screw up soon. Apologies for the delay.

On Thu, Jun 15, 2017 at 13:06 Lorenzo Miniero

<
mailto:Lorenzo Miniero <notifications@github.com>
> wrote:

a, pre, code, a:link, body { word-wrap: break-word !important; }

https://github.com/joshdickson40
did you manage to make any progress here?

—

You are receiving this because you were mentioned.

Reply to this email directly,
https://github.com/meetecho/janus-gateway/pull/898#issuecomment-308805856
, or

**Comment by lminiero** [comment]
No problem, I just thought I'd ping!

**Comment by lminiero** [comment]
Ping :smile:

**Comment by idi-ot** [comment]
Since `libnice 0.1.14` is not a problem anymore and it is in `brew`
```sh
> brew info libnice
libnice: stable 0.1.14 (bottled)
GLib ICE implementation
https://wiki.freedesktop.org/nice/
/usr/local/Cellar/libnice/0.1.14 (82 files, 2.5MB) *
  Poured from bottle on 2018-01-02 at 13:51:10
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libnice.rb
==> Dependencies
Build: pkg-config ✔
Required: glib ✔, gnutls ✔, gstreamer ✔
```
I think `brew tap homebrew/boneyard` can be removed altogether from the installation guide.

**Comment by lminiero** [comment]
@idi-ot thx!

**Comment by idi-ot** [comment]
@lminiero it seems like I have installed janus
```sh
> bin/janus --help
Janus commit: 345641443fa073b4274cf6eabe5b190077629cce
Compiled on:  Wed Jan  3 15:15:54 UTC 2018

janus 0.3.0
...
```
with just the following comamnds

```sh
> brew install libwebsockets libmicrohttpd srtp jansson libnice openssl libwebsockets cmake opus libogg glib pkg-config gengetopt autoconf automake libtool

> git clone https://github.com/meetecho/janus-gateway.git
> cd janus-gateway

> sh autogen.sh

> ./configure --prefix=/usr/local/janus PKG_CONFIG_PATH=/usr/local/opt/openssl/lib/pkgconfig

> make
> make install
> make configs
```

**Comment by lminiero** [comment]
Ack, thanks for the heads up! If you can let me know whether it seems to work for you, I'll make sure to update the README with your suggestions :+1:

**Comment by idi-ot** [comment]
@lminiero everything except for websockets https://github.com/meetecho/janus-gateway/issues/1124 seems to be working fine. I've tried running janus in a docker container [krull/docker-janus](https://github.com/krull/docker-janus), and so far websockets  don't cause any problems.

**Comment by lminiero** [comment]
@idi-ot the fix for libwebsockets on Mac OS was discussed here: https://groups.google.com/forum/#!topic/meetecho-janus/HsFaEXBz4Cg
Not sure if specific instructions can be devised from that?

**Comment by idi-ot** [comment]
That thread answered every question I had about this issue with websockets. I think it might be helpful for others as well.

I meant that a note could just say that there might be problems with `libwebsockets 2.4.1` on mac and point to this discussion.

**Comment by lminiero** [comment]
I integrated @idi-ot's suggestions in the README, so now the instructions should be fixed and we can close this. Please let me know if I overlooked something and the README needs revisiting. Thx!

**Comment by idi-ot** [comment]
@lminiero it's also possible to install `libsrtp` with `brew`, `brew install srtp`.

I don't think it's in here

```
brew install jansson libnice openssl libusrsctp libmicrohttpd libwebsockets cmake rabbitmq-c sofia-sip opus libogg curl glib pkg-config gengetopt autoconf automake libtool

```

**Comment by lminiero** [comment]
Ops you're right, I forgot to add that, thanks for spotting this :+1:

**Pull request closed without merging**
