### PR TITLE
sip: fixed reporting re-INVITEs as missed calls

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by lminiero** [comment]
Will Sofia simply reply with the SDP it had previously?

**Comment by saghul** [comment]
Yep, that's what my tests showed.

**Comment by lminiero** [comment]
Ok, I guess it's safe to merge then, thanks!

**Comment by saghul** [comment]
It does increase the SDP version number, in order to behave like a good citizen :-)

**Comment by lminiero** [comment]
:+1:

**Pull request merged**
