### PR TITLE
ice: avoid crash on NACK cleanup

### LINKED ISSUE #1453: Segfault in  janus_ice_nacked_packet_cleanup
This is hard to reproduce, but using commit c0e9577b I hit the following segfault:

```
janus.log:ASAN:DEADLYSIGNAL
janus.log-=================================================================
janus.log-==13==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000320 (pc 0x557b4c81dec1 bp 0x7f6399eed4e0 sp 0x7f6399eed2f0 T50)
janus.log-==13==The signal is caused by a READ memory access.
janus.log-==13==Hint: address points to the zero page.
janus.log-#0 0x557b4c81dec0 in janus_ice_nacked_packet_cleanup /tmp/janus-gateway/ice.c:330
janus.log-#1 0x7f63b0caac72  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4cc72)
janus.log-#2 0x7f63b0caa1f4 in g_main_context_dispatch (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c1f4)
janus.log-#3 0x7f63b0caa5bf  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c5bf)
janus.log-#4 0x7f63b0caa8d1 in g_main_loop_run (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x4c8d1)
janus.log-#5 0x557b4c842ae9 in janus_ice_handle_thread /tmp/janus-gateway/ice.c:1056
janus.log-#6 0x7f63b0cd2104  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x74104)
janus.log-#7 0x7f63af7f26da in start_thread (/lib/x86_64-linux-gnu/libpthread.so.0+0x76da)
janus.log-#8 0x7f63af51b88e in __clone (/lib/x86_64-linux-gnu/libc.so.6+0x12188e)
janus.log-
janus.log-AddressSanitizer can not provide additional info.
janus.log-SUMMARY: AddressSanitizer: SEGV /tmp/janus-gateway/ice.c:330 in janus_ice_nacked_packet_cleanup
janus.log-Thread T50 (hloop 618052118) created by T9 here:
janus.log-#0 0x7f63b1656d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
janus.log-#1 0x7f63b0cefe2f  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x91e2f)
janus.log-
janus.log-Thread T9 created by T0 here:
janus.log-#0 0x7f63b1656d2f in __interceptor_pthread_create (/usr/lib/x86_64-linux-gnu/libasan.so.4+0x37d2f)
janus.log-#1 0x7f63b0cefe2f  (/usr/lib/x86_64-linux-gnu/libglib-2.0.so.0+0x91e2f)
janus.log-
```

Is it possible that this timeout:
https://github.com/meetecho/janus-gateway/blob/c0e9577b06862c7d90461eda24cd2c0257c30cad/ice.c#L330

is being invoked due the timeout created here:
https://github.com/meetecho/janus-gateway/blob/c0e9577b06862c7d90461eda24cd2c0257c30cad/ice.c#L2496

after this block is invoked?
https://github.com/meetecho/janus-gateway/blob/c0e9577b06862c7d90461eda24cd2c0257c30cad/ice.c#L1400

### PR DESCRIPTION
**Pull request by tmatth**
Fixes #1453

### CODE REVIEW

**Comment by atoppi** [comment]
After a second review of the issue, I think that managing the source pointer is not possible, because multiple timeout sources can be settled up, and so we could only save the last one.
The only condition to setup a timeout source is
`cur_seq->state == SEQ_MISSING && now - cur_seq->ts > SEQ_MISSING_WAIT`
and this means that for every missing packet, after 12ms, we'll send a nack and set a cleanup task timeout. So having multiple concurrent timeout sources is a frequent scenario.

**Comment by tmatth** [comment]
@atoppi so do you think the NULL check alone is sufficient? My concern there (and rationale for the refcount approach) was that the timeout is fired off from a different thread then the thread which invokes `janus_ice_stream_free`.

**Comment by tmatth** [comment]
@lminiero ok I've updated the PR

**Comment by lminiero** [comment]
Looks good to me :+1: 
Merging, thanks!

**Pull request merged**
