### PR TITLE
Support ontrack

### PR DESCRIPTION
**Pull request by joshdickson40**
This PR adds support for the [RTCPeerConnection.ontrack](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/ontrack) event in `janus.js` (as well as `janus.nojquery.js`, of course!) 

Currently, `janus.js`uses [RTCPeerConnection.onaddstream](https://developer.mozilla.org/en-US/docs/Web/API/RTCPeerConnection/onaddstream) which has been removed from Web standards. Firefox has marked it deprecated (see #806).

As of right now, the only browser to implement `ontrack` is Firefox. Fortunately, `webrtc-adapter.js` is now supporting an `ontrack` shim as of [3.4.1](https://github.com/webrtc/adapter/releases/tag/v3.4.1) which makes it possible for Janus to cleanly move from `onaddstream` to `ontrack` and not deal with any of the particulars.

Aside from updating the adapter version and event name, the only change here is to deal with the fact that the event received by `ontrack` is different than the event received by `onaddstream` (particularly in that it receives an array of streams rather than a single stream.)

Feedback, testing, etc, welcome :)

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks, this is most welcome! How come it returns an array of streams? Are there cases where you could end up with more than one in the callback?

**Comment by joshdickson40** [comment]
See [example here](https://w3c.github.io/webrtc-pc/#h-advanced-peer-to-peer-example-with-warm-up) where they combine a video and audio stream in the same track.

```
// once remote track arrives, show it in the remote video element
pc.ontrack = function (evt) {
  if (evt.track.kind === "audio") {
      if (answerer) {
        audio = evt.transceiver;
        audio.setDirection("sendrecv");
        if (started && audioSendTrack) {
          audio.sender.replaceTrack(audioSendTrack);
        }
      }
    } else if (evt.track.kind === "video") {
      if (answerer) {
        video = evt.transceiver;
        video.setDirection("sendrecv");
            if (started && videoSendTrack) {
              video.sender.replaceTrack(videoSendTrack);
            }
          }
        }
        // don't set srcObject again if it is already set.
        if (!remoteView.srcObject)
          remoteView.srcObject = evt.streams[0];
    };
```

**Comment by lminiero** [comment]
I'll give it a try as soon as I have some time to give my feedback. If others could do the same that would help merge it sooner. I'll also add this to the list of PRs to check on the group.

**Comment by lminiero** [comment]
Tested and it looks fine to me, so I'll be brave and merge :smile: 
Thanks again for the fix!

**Comment by lminiero** [comment]
@joshdickson40 I should have played with this more... Just found that it looks like this breaks Firefox, so I'm going to revert the change you made in janus[.nojquery].js. When we find a fix that works for both Chrome and Firefox we can restore it.

**Comment by joshdickson40** [comment]
How does it fail? I tested this on Firefox 47 and 53 (current) before PRing and I'm re-testing it now without issue.

**Comment by lminiero** [comment]
For us, just testing the echotest would result in a "no video available" box, on both Firefox 53 and 55. It happened on three different systems, Linux and Windows alike.

**Comment by joshdickson40** [comment]
Got it, this must be a video thing because my audio testing is all passing. Let me try to replicate it this weekend and I can perhaps open a new PR once I have more information on what needs to change.

**Comment by lminiero** [comment]
Yep, I think that only one of the two tracks is going through, and so even if the browser is receiving video (the stats confirm this) the stream only contains audio and so video is not rendered.

**Comment by joshdickson40** [comment]
Okay, thanks Lorenzo. Sorry for the trouble!

**Comment by lminiero** [comment]
No problem at all! It's actually my fault as I should have done some more tests. Thanks for your help and support on all this!

**Pull request merged**
