### PR TITLE
CMake implementation

### PR DESCRIPTION
**Pull request by SamuelMarks**
Just started CMake for you.

Do you want it?

If so, next I'll add 3rd-party library support with [`find_package`](https://cmake.org/cmake/help/latest/command/find_package.html) and [`target_link_libraries`](https://cmake.org/cmake/help/latest/command/target_link_libraries.html).

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @SamuelMarks! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Comment by lminiero** [comment]
While I appreciate the (huge!) effort, we're not looking for a cmake replacement for autoconf/automake at the moment. Our setup is quite complex, with a lot of optional modules and applications, so it's not just Janus itself. Even with a perfect drop-in replacement (and from a quick glance this is just a portion of the work), considering we're not familiar with cmake (or at least I'm definitely not) this would make it much harder for us to mantain or update when new stuff is added. Besides, we're about to merge the `multistream` branch, and so any refactoring of tooling of these proportions would need to wait until that happens anyway.

**Comment by SamuelMarks** [comment]
Ok maybe just tag me when multistream is merged and I'll see what I can do

**Comment by lminiero** [comment]
Ack, closing this for now.

**Pull request closed without merging**
