### PR TITLE
 Add Python aiortc-based functional testing.

### PR DESCRIPTION
**Pull request by atoppi**
This PR adds a very minimal functional testing for Janus.
The only proposed test, as of now, is a Python script based on [aiortc](https://github.com/aiortc/aiortc) (`echo.py`) that basically implements an echotest session and evaluates some WebRTC related assertions (ICE, DTLS, RTP and so on).
We're also providing a helper script (`test_aiortc.sh`) that you can launch to quickly start a test.
Both `echo.py` and `test_aiortc.sh` return 0 for a successful execution. This should facilitate future integrations with continuous testing frameworks.

In order to test the script you'll need to have working Janus binaries in the parent directory and working Janus configurations installed in the `prefix` path specified in the `configure`.

Example of the output
```
atoppi@atoppi:~/src/janus-gateway$ ./test/test_aiortc.sh
Starting Janus binary from /home/atoppi/src/janus-gateway ...
Waiting for some seconds before launching the test ...
Launching test /home/atoppi/src/janus-gateway/test/echo.py ...
INFO:echo:Creating session
INFO:echo:WebSocket connected
INFO:echo:Session created
INFO:echo:Attaching handle
INFO:echo:Handle attached
INFO:echo:Sending message to the plugin
INFO:echo:Janus Event --> event
INFO:echo:Track audio received
INFO:echo:Track video received
INFO:echo:Running for a while...
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.169', 40934) -> ('192.168.1.169', 36351)) State.FROZEN -> State.WAITING
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.169', 40934) -> ('192.168.1.169', 36351)) State.WAITING -> State.IN_PROGRESS
INFO:ice:Connection(0) Check CandidatePair(('192.168.1.169', 40934) -> ('192.168.1.169', 36351)) State.IN_PROGRESS -> State.SUCCEEDED
INFO:ice:Connection(0) ICE completed
INFO:echo:Janus Event --> webrtcup
INFO:echo:Janus Event --> media
INFO:echo:Janus Event --> media
INFO:echo:Ending the test now
INFO:echo:Test Passed
INFO:echo:Destroying session
INFO:echo:Janus Event --> event
INFO:echo:Session destroyed
INFO:echo:Closing WebSocket
INFO:echo:Connection closed
TEST SUCCEDED
```

For more details please refer to the README file.

### CODE REVIEW

**Comment by tmatth** [comment]
@atoppi you may want to add a `requirements.txt` file so that you can pin versions of the dependencies in here and use for e.g., a virtualenv. This will be a lot more robust across distros and for CI.

**Comment by arpu** [comment]
looks like if i use the Janussession with different plugin the session timeouts after some time 
maybe there must be a  session ping pong? like https://github.com/aiortc/aiortc/blob/master/examples/janus/janus.py#L87 ( for http api)

**Comment by atoppi** [comment]
@arpu I have added a keep-alive task.
Please notice that I did it just for sake of completeness and as a personal exercise, because in general the script is not meant to be used as a full Janus API wrapper.

**Comment by arpu** [comment]
this is awesome!  the idea is for me make a webrtc client that can receive video audio tracks to send to ffmpeg

**Comment by lminiero** [comment]
Merging :+1:

**Pull request merged**
