### PR TITLE
Reconnect RTSP stream if it goes down (Streaming plugin)

### PR DESCRIPTION
**Pull request by lminiero**
This PR tries to address the issue @fbertone highlighted in #845.

Tested briefly and seems to be working as expected with the simple RTSP server I used for testing, but of course this needs more testing with something real and in real scenarios. Please play with it and provide feedback.

### CODE REVIEW

**Comment by fbertone** [comment]
Thanks for the very fast implementation!
Just recompiled & tested.
The first time it reconnects smoothly and the stream get restarted without any problem.
However, the second time in a row that it get disconnected it crashes badly.

```
[WARN] [rtsp-cam1] 5s passed with no media, trying to reconnect the RTSP stream
[ERR] [plugins/janus_streaming.c:janus_streaming_rtsp_connect_to_server:3256] Couldn't send DESCRIBE request: Timeout was reached
[WARN] [rtsp-cam1] Reconnection of the RTSP stream failed, trying again in a few seconds...
[WARN] [rtsp-cam1] 5s passed with no media, trying to reconnect the RTSP stream
[rtsp-cam1] New video stream! (ssrc=3819561593)
[WARN] [rtsp-cam1] 5s passed with no media, trying to reconnect the RTSP stream
Segmentation fault (core dumped)
```

I have not reviewed the code just yet, but the error in the log let me think it could be something related to the 'send DESCRIBE' loop that is not cleanly restarted or something like that?
Tomorrow I will test the code also on a different setup.

**Comment by lminiero** [comment]
I can't replicate this with my simple RTSP server: restarted more than once and it always managed to reconnect, with working media. This RTSP server is not using authentication, though, so it may be an issue with credentials possibly? If you can get some debug out of this it would help.

**Comment by fbertone** [comment]
It actually crashes even if I just pull the cable the first time and just leave it disconnected. Maybe you can replicate that?

```
[rtsp-cam1] New video stream! (ssrc=3791157077)
[WARN] [rtsp-cam1] 5s passed with no media, trying to reconnect the RTSP stream
*   Trying 192.168.0.10...
* TCP_NODELAY set
* Connection timed out after 10001 milliseconds
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
[ERR] [plugins/janus_streaming.c:janus_streaming_rtsp_connect_to_server:3256] Couldn't send DESCRIBE request: Timeout was reached
[WARN] [rtsp-cam1] Reconnection of the RTSP stream failed, trying again in a few seconds...
[WARN] [rtsp-cam1] 5s passed with no media, trying to reconnect the RTSP stream
*   Trying 192.168.0.10...
* TCP_NODELAY set
* Connection timed out after 10001 milliseconds
* Curl_http_done: called premature == 1
* stopped the pause stream!
* Closing connection 0
[ERR] [plugins/janus_streaming.c:janus_streaming_rtsp_connect_to_server:3256] Couldn't send DESCRIBE request: Timeout was reached
[WARN] [rtsp-cam1] Reconnection of the RTSP stream failed, trying again in a few seconds...
[rtsp-cam1] 40s passed, sending GET_PARAMETER
Segmentation fault (core dumped)
```

wait, in the last line isn't it trying to send the GET_PARAMETER request through a socket that is not instantiated maybe?

**Comment by lminiero** [comment]
> wait, in the last line isn't it trying to send the GET_PARAMETER request through a socket that is not instantiated maybe?

I think that's it, my test RTSP server doesn't specify a timeout so I never get into that branch. I just pushed a check that should fix it, let me know if that works for you.

**Comment by fbertone** [comment]
Yes, this last commit solved the problem!

**Comment by lminiero** [comment]
Great! Waiting for your feedback on whether this can be merged, then, in case you can make some more tests with the RTSP servers you usually talk to :+1:

**Comment by lminiero** [comment]
Pushed another fix that could cause a deadlock if connecting to an RTSP stream when creating the mountpoint failed: in fact, when refactoring the connection part to use a different method, I forgot to unlock the global mountpoint mutex in case of errors.

**Comment by lminiero** [comment]
Merging as it seems to be working for me, and I'd like to sync the reference counters branch with master today (many conflicts I have to address already). In case you spot any weir behaviour, feel free to open a new issue.

**Comment by fbertone** [comment]
Seems to be working for all my environments.
Thanks

**Pull request merged**
