### PR TITLE
Introduce Janus JS logger

### PR DESCRIPTION
**Pull request by yan-foto**
As I was lost in the huge amount of logs, which are produced by `janus.js` when debugging is enabled, I created as simple logger with log level support which makes use of browsers `console.trace`, `console.warn`, etc. and provides fallback methods if these are not supported.

If it is something desirable, I could go ahead and replace `Janus.log` in javascript code with appropriate methods of the logger before the merge.

### CODE REVIEW

**Comment by lminiero** [comment]
That looks realy interesting! I'll look into it when I get back home (still abroad).
That said, before I can merge this, I'd ask you to sign our CLA if you haven't done that yet:
https://cla.conf.meetecho.com/janus/

Thanks!

**Comment by yan-foto** [comment]
Agreement is signed.

**Comment by lminiero** [comment]
Yep, I get that :smile: 

It definitely looks like something that would improve things. Can you adapt just one of the demos (e.g., echo test or whatever you use the most) just to see how it would look like?

Thanks!

**Comment by yan-foto** [comment]
I enhanced the logger and used it in `streamingtest.js`. However to have clean output It should be added to `janus.js` first and foremost!

**Comment by yan-foto** [comment]
I enhanced the logger and used it in `streamingtest.js`. However to have clean output It should be added to `janus.js` first and foremost!

**Comment by yan-foto** [comment]
Any updates on this?

**Comment by lminiero** [comment]
Sorry, github apparently didn't notify me about the further changes you made 5 days ago and I'm only now seeing them... I'll check on Monday when I get back to work. Thanks!

**Comment by lminiero** [comment]
Sorry for the abysmal delay, just manager to get to this after my vacation... just tested and this looks great, thanks!

Just wondering if we can make this slightly more "transparent" than creating a logger specifically. Namely, for now we have a generic ```Janus.log``` that either prints something or doesn't, according to what you passed as the ```debug``` value in ```Janus.init```. My feeling is that this new logging approach belongs to the ```init``` as well, as conceptually you shouldn't have a logger before you initialized the library: besides, it being outside of the ```init``` might make it less clear on what should be done within ```janus.js``` itself.

Not sure what the best way to proceed on this would be: one way could be creating wrappers called ```Janus.trace```, ```Janus.warn``` etc. pretty much as we do for ```Janus.log=console.log```, and then turning the ```debug``` value in init from boolean to something else (e.g., numeric identifier for logging level, comma separated list of stuff you want logged, etc.). What's your feeling about this? This is not something I'd ask you to do, of course: I can take care of this starting from the examples you provided.

Thanks again!

**Comment by yan-foto** [comment]
> My feeling is that this new logging approach belongs to the init as well, as conceptually you shouldn't have a logger before you initialized the library

I do absolutely agree with you. I think its a good idea to initialize the logger inside init and expose it through the wrappers as you mentioned.

> What's your feeling about this?

Big Picture: to be honest as I was trying to integrate `janus.js` into a project, and I would say (thinking on #310) we need to extract the javascript framework from the main structure and let it exist as its own module. I could most definitely give a hand to conceptualize and kick start a `janus.js` module.

**Comment by lminiero** [comment]
> I do absolutely agree with you. I think its a good idea to initialize the logger inside init and expose it through the wrappers as you mentioned.

Ok, I'll craft a new version of ```janus.js``` deriving from your changes. I'll probably create a new PR for that, I'll notify it here.

> Big Picture: to be honest as I was trying to integrate janus.js into a project, and I would say (thinking on #310) we need to extract the javascript framework from the main structure and let it exist as its own module. I could most definitely give a hand to conceptualize and kick start a janus.js module.

Not sure I understand, but everything that can make it easier to integrate elsewhere would be more than welcome! If you have ideas on how to do that (I'm unfortunately all but a JavaScript wizard, I'm afraid) that would be great.

**Comment by yan-foto** [comment]
Sorry I have this problem of not being able to express myself!

At the moment if someone wants to use the JS module, he should try to make sense of the files included under `html` directory and copy them into their own projects. My suggestion is to have an npm package to be used in CommonJS compatible environments and a bower package for everyone who wants to have it inside the browser. It would be easier this way to build a modular project and maintain dependencies.

**Comment by lminiero** [comment]
Ah in this case I'm not so sure about it... I'm not a fan of frameworks, and I don't want to constrain our JavaScript library to any of them. Different people use different things, and forcing them to rely, e.g., on bower/npm could prevent them from integrating it somewhere else.

**Comment by yan-foto** [comment]
I can understand your concerns. But let me put it this way: we will have a separate repository with the following structure:

```
|-- dist
|   |-- janus.js
|   |-- stream.plugin.js
|-- src
|   |-- janus.es6
|   |-- stream.plugin.es6
|   |-- other-deps.es6
|-- gulpfile.js
|-- bower.json
|-- package.json
```

Everyone who needs the production version uses the ready-to-use file available under `dist` or let bower (see `bower.json`) download it. The others who want to use it in CommonJS environments can just use the npm package (see `package.json`). Moreover the project will be easier to maintain using a build system such as gulp (see `gulpfile.js`).

Does it make sense?

**Comment by lminiero** [comment]
I eventually integrated part of your approach in janus.js, so that we now also have Janus.trace, Janus.debug, etc. The way you selectively enable and disable them is through the pre-existing ```debug``` attribute in Janus.init: passing ```true``` or ```"all"``` enables them all, ```false``` disables debugging entirely, and an array similar to the ```methods``` you had (e.g., ```debug: ["warn", "error", "log"]```) makes sure that only the ones you chose be printed.

Thanks for your feedback and help on this!

**Pull request closed without merging**
