### PR TITLE
SIP plugin: Fixed update request for SRTP sessions

### PR DESCRIPTION
**Pull request by ihusejnovic**
Hi,
This pull request is a fix for update request when SIP session is using SDES-SRTP, as I promised in my previous pull request :)

When you confirm that this is fine I will apply it to NoSIP plugin too.

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! This looks good to me :+1: 
And thanks for volunteering to fix NoSIP too! Would you do that in this PR, or in another one?

**Comment by ihusejnovic** [comment]
Thank you. I will update this pull request.

**Comment by lminiero** [comment]
Ack, then I'll wait for that before merging :+1:  Thanks again!

**Comment by lminiero** [comment]
@ihusejnovic I decided to merge this as it is. We can worry about NoSIP later. Thanks!

**Comment by ihusejnovic** [comment]
@lminiero ok, I have started working on NoSIP plugin but then I realized that SRTP is not working fine for the "process" request at all. I'm also trying to fix that. Hopefully, a new pull request will arrive soon. :)

**Pull request merged**
