### PR TITLE
release sessions_mutex in case of the error

### PR DESCRIPTION
**Pull request by garry81**

### CODE REVIEW

**Comment by lminiero** [comment]
Good catch, thanks! Can you fill in the form of our [CLA](https://cla.conf.meetecho.com/janus/) so that we can merge this?

**Comment by garry81** [comment]
done

**Comment by lminiero** [comment]
Thanks, merging then!

**Comment by lminiero** [comment]
Just noticed the same problem in a couple of other plugins (plus a typo, missing "No " in the text in the same branch), so I'll apply the fix to those myself.

**Pull request merged**
