### PR TITLE
fix for janus_videoroom_listener leak for janus_videoroom_listener_muxed

### PR DESCRIPTION
**Pull request by mtdxc**
i has find memleaks when i use janus_videoroom_listener_muxed 
it don't free any janus_videoroom_listener , this is the pactch i made for it
can you check if is ok and then merge with master .

### CODE REVIEW

**Comment by ploxiln** [comment]
This forgets to free the GSList nodes. You can just add `g_slist_free(l->listeners)` after you free all the listeners.

(Also the added log line is redundant, I'd remove the original)

**Comment by lminiero** [comment]
Yep, the suggestions made by @ploxiln would definitely improve things.

That said, the muxed listeners part probably needs much more work than just this leak fix, as we never devoted much effort on making it really usable. It will probably become obsolete anyway when we start working on the Unified Plan refactoring early next year, which will make multiple streams supported at the core level itself.

**Comment by lminiero** [comment]
PS: have you signed our [CLA](https://cla.conf.meetecho.com/janus/)? We need this for every contribution by new authors before we can merge.

**Comment by mtdxc** [comment]
yes I have accept the  @ploxiln suggestions and signed CLA. 
please recheck it

**Comment by lminiero** [comment]
Looks fine, thanks :+1:

**Pull request merged**
