### PR TITLE
http transport ipv6 fixes for nonipv6 systems

### PR DESCRIPTION
**Pull request by sdrsdr**
A pull reqest about issue #923

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks for this PR, although a system-specific check on `/proc/net/if_inet6` is not my favourite way of handling that. My guess is that we should simply add a new setting in `janus.transport.http.cfg` that says something like `ipv6 = yes|no`, so that people can specify this themselves. Ideally we'd want to re-use the one in `janus.cfg`, but as I was saying we don't have any way to get that info to transports right now without a change in the internal transport plugins API. This would free us from system-specific stuff, and allow users to configure that themselves depending on their system. I can work on this new feature later.

**Comment by sdrsdr** [comment]
What if we try to enable dual stack only if specifially configured to bind to 0:0:0:0 or the ipv6 equivalent. This way the "default" config will be safer and will diable possibly incompatible behavior?

**Comment by lminiero** [comment]
The default behaviour is to bind to everything, and this would be incomplete without the possibility to bind to both ipv6 and ipv4 as it does now. That's why a simple on/off flag sounds like an easier way to do this, at least for me. We can make the default for ipv6 to be `false` so that ot doesn't break on systems like yours.

**Comment by sdrsdr** [comment]
Well .. trying to bind to something not supported end in the whole transport totally unavailable ... I got my problem fixed, and if I've put ip=0.0.0.0 in my config I think I can go with "stock" version so feel free to solve the problem any way you like :) I'll be glad to test the solution you provide  :)

**Comment by lminiero** [comment]
That's actually a good point: we probably don't need an ipv6 flag in the config, as we can already use the interface setting to do exactly that. The default binds to everything, setting `0.0.0.0` binds to IPv4 only. I'll make this more explicit in the config file comments, so that this shouldn't be an issue in the future.

**Comment by lminiero** [comment]
The IPv6 equivalent is `::`, so setting that would only bind to IPv6.

**Comment by sdrsdr** [comment]
just tried today to bind to 0.0.0.0 but this failed as it is treated as invalid IP i gess binding to 192... works fine but preents 127.0.0.1 to work ..

**Comment by lminiero** [comment]
Darn, and here I hoped this would be easy! :smile:

**Comment by sdrsdr** [comment]
Well I can track it down for you and fix it if you like ;)

**Comment by lminiero** [comment]
Yep, was just thinking of adding a manual check for "0.0.0.0" and "::" to the code, to do the right thing without too many checks. Was this what you meant by tracking down?

**Comment by sdrsdr** [comment]
yes

**Comment by sdrsdr** [comment]
it depends how the code is written it might be easy to be done more cleanly

**Comment by lminiero** [comment]
If you have a PR ready I'll gladly accept that! :grin: 
Otherwise I can take care of that myself, no worries.

**Comment by sdrsdr** [comment]
btw are the config values trimmed? as this might be hard to spot

**Comment by lminiero** [comment]
Yes, the config parser trims them.

**Comment by sdrsdr** [comment]
I don't have anything ready but I'm on this codebase, I can fix this at some point

**Comment by lminiero** [comment]
I'm thinking to add the check at the very beginning of this branch here: https://github.com/meetecho/janus-gateway/blob/master/transports/janus_http.c#L259

Basically, if it's "0.0.0.0", fill `addr` and set `addr.sin_addr` to `INADDR_ANY`; if it's "::", fill `addr6` and set `addr6.sin6_addr` to `in6addr_any`. This should be transparent to the rest of the code, as `addr` and `addr6` are what we then pass to libmicrohttpd.

I'll work on a commit shortly so that you can test this later.

**Comment by sdrsdr** [comment]
great :)

**Comment by lminiero** [comment]
This commit seems to fix it for me. Noticed that if you set `::` it does NOT bind to IPv6 only, but still does IPv4 and IPv6. Apparently that's due to how dual stack systems work.

**Comment by sdrsdr** [comment]
Works here also :) Good work! 👏

**Pull request closed without merging**
