### PR TITLE
update dtls ciphers

### PR DESCRIPTION
**Pull request by fippo**
following https://github.com/versatica/mediasoup/issues/367
Been using the same set for years without interop problems

Thanks @ibc for the poke

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks @fippo! I've actually made ciphers configurable in #1992, though, and I think the (commented) value in the config is that one indeed (the one Chrome uses I think?). If you say that works fine, I'll make it the default there then :+1:

**Comment by ibc** [comment]
"I don't know what the f*** those ciphers mean so I let the users choose it"

**Comment by fippo** [comment]
@ibc will be happy to hear there are more people using those cool ciphers.
Lets burn some trash :-)

**Comment by lminiero** [comment]
Merging, I'll align the other PR accordingly :+1:

**Comment by ibc** [comment]
AMAZING!

**Comment by lminiero** [comment]
> AMAZING!

:stuck_out_tongue_closed_eyes:

**Comment by ibc** [comment]
This PR is amazing. Now I have a second problem. Can you create simple code snippets? You must do it because I don't want to learn Janus in depth but just use it and make money with it.

**Comment by lminiero** [comment]
Of cour :heavy_dollar_sign:  e!

**Comment by ibc** [comment]
BUT this would be good for you because the open source.

**Comment by lminiero** [comment]
Sorry, I'm busy!

**Comment by ibc** [comment]
WHY? YOU ARE AT HOME YOU CANNOT LEAVE

**Comment by fippo** [comment]
lets call the :policeman: -- guardia di finanza would be appropriate since this is about :heavy_dollar_sign: :heavy_dollar_sign:

**Pull request merged**
