### PR TITLE
Fix typo in sdp-utils.h

### PR DESCRIPTION
**Pull request by Mahmo0odsalah**
default instead of defaukt

### CODE REVIEW

**Comment by tmatth** [comment]
While you're looking, there are some others (some of these are false positives):

```
tmatth@bellini:~/src/janus-gateway$ find -name *.c | xargs codespell 
./fuzzers/rtp_fuzzer.c:40: Verifing ==> Verifying
./src/sdp.c:1528: advertize ==> advertise
./src/postprocessing/janus-pp-rec.c:1091: resetted ==> reset
./src/postprocessing/janus-pp-rec.c:1111: ot ==> to, of, or, not
./src/events.c:178: compatbility ==> compatibility
./src/events/janus_mqttevh.c:485: succesful ==> successful
./src/events/janus_mqttevh.c:554: propably ==> probably
./src/events/janus_mqttevh.c:584: propably ==> probably
./src/transports/janus_mqtt.c:272: statics ==> statistics
./src/sctp.c:580: eror ==> error
./src/ice.c:166: keep-alives ==> keep-alive
./src/ice.c:171: keep-alives ==> keep-alive
./src/ice.c:3264: re-negotation ==> re-negotiation
./src/plugins/janus_videocall.c:95: successul ==> successful
./src/plugins/janus_videocall.c:120: successul ==> successful
./src/plugins/janus_videocall.c:156: successul ==> successful
./src/plugins/janus_lua_extra.c:6: viceversa ==> vice-versa
./src/plugins/janus_recordplay.c:2623: resetted ==> reset
./src/plugins/janus_recordplay.c:2638: ot ==> to, of, or, not
./src/plugins/janus_recordplay.c:2699: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2713: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2714: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2727: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2728: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2729: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2743: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2744: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2745: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2756: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2757: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2758: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2775: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2776: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2777: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2786: asent ==> ascent
./src/plugins/janus_recordplay.c:2809: asent ==> ascent
./src/plugins/janus_recordplay.c:2813: asent ==> ascent
./src/plugins/janus_recordplay.c:2819: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2820: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2852: asent ==> ascent
./src/plugins/janus_recordplay.c:2868: asent ==> ascent
./src/plugins/janus_recordplay.c:2881: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2882: afile ==> a file, agile
./src/plugins/janus_recordplay.c:2911: asent ==> ascent
./src/plugins/janus_recordplay.c:3057: afile ==> a file, agile
./src/plugins/janus_recordplay.c:3058: afile ==> a file, agile
./src/plugins/janus_recordplay.c:3059: afile ==> a file, agile
./src/plugins/janus_videoroom.c:601: overrided ==> overrode, overridden
./src/plugins/janus_videoroom.c:602: overrided ==> overrode, overridden
./src/plugins/janus_videoroom.c:9665: Soemthing ==> Something
./src/plugins/janus_duktape_extra.c:6: viceversa ==> vice-versa
./src/plugins/janus_audiobridge.c:814: adviced ==> advised
./src/plugins/janus_audiobridge.c:7672: setted ==> set
./src/plugins/janus_streaming.c:91: analisys ==> analysis
./src/plugins/janus_streaming.c:105: analisys ==> analysis
./src/plugins/janus_streaming.c:2319: chech ==> check, czech
./src/plugins/janus_streaming.c:2353: chech ==> check, czech
./src/plugins/janus_streaming.c:2562: chech ==> check, czech
./src/plugins/janus_streaming.c:2636: chech ==> check, czech
./src/plugins/janus_streaming.c:2730: chech ==> check, czech
./src/plugins/janus_streaming.c:2736: chech ==> check, czech
./src/plugins/janus_streaming.c:3468: chech ==> check, czech
./src/plugins/janus_streaming.c:3596: chech ==> check, czech
./src/plugins/janus_streaming.c:3666: chech ==> check, czech
./src/plugins/janus_streaming.c:3859: chech ==> check, czech
./src/plugins/janus_streaming.c:3949: chech ==> check, czech
./src/plugins/janus_streaming.c:4089: chech ==> check, czech
./src/plugins/janus_streaming.c:4094: chech ==> check, czech
./src/plugins/janus_streaming.c:5919: uneeded ==> unneeded, unheeded, needed
./src/plugins/janus_streaming.c:6860: viceversa ==> vice-versa
./src/plugins/janus_streaming.c:8273: keep-alives ==> keep-alive
./src/plugins/janus_streaming.c:8453: keep-alives ==> keep-alive
./src/plugins/janus_streaming.c:9297: keep-alives ==> keep-alive
./src/plugins/janus_sip.c:1535: utilies ==> utilities
./src/plugins/janus_sip.c:5652: ourselfes ==> ourselves
./src/plugins/janus_sip.c:5683: authetntication ==> authentication
./src/plugins/janus_sip.c:5683: registerered ==> registered
./src/janus-cfgconv.c:4: viceversa ==> vice-versa
./src/sdp-utils.c:2211: mesage ==> message
./src/dtls.c:105: aNULL ==> annul
./src/rtcp.c:361: separetely ==> separately
./src/rtcp.c:374: separetely ==> separately
./src/rtcp.c:1851: chunck ==> chunk
```

```
tmatth@bellini:~/src/janus-gateway$ find -name *.h | xargs codespell 
./src/mach_gettime.h:24: compatability ==> compatibility
./src/mach_gettime.h:38: environement ==> environment
./src/mach_gettime.h:44: initilized ==> initialized
./src/mach_gettime.h:47: numer ==> number
./src/mach_gettime.h:56: coresponding ==> corresponding
./src/utils.h:61: occured ==> occurred
./src/utils.h:68: occured ==> occurred
./src/rtpfwd.h:63: swtiching ==> switching
./src/rtpfwd.h:99: successfull ==> successful
./src/dtls.h:73: handhake ==> handshake
./src/events/eventhandler.h:58: callack ==> callback
./src/mutex.h:3: Semaphors ==> Semaphores
./src/apierror.h:29: suppurt ==> support
./src/config.h:79: sav ==> save
./src/loggers/logger.h:48: callack ==> callback
./src/plugins/plugin.h:488: jave ==> java, have
./src/plugins/janus_lua_data.h:6: viceversa ==> vice-versa
./src/plugins/janus_lua_extra.h:6: viceversa ==> vice-versa
./src/plugins/janus_duktape_extra.h:6: viceversa ==> vice-versa
./src/plugins/janus_duktape_data.h:6: viceversa ==> vice-versa
./src/rtcp.h:305: quering ==> querying
./src/rtcp.h:310: quering ==> querying
./src/sdp-utils.h:171: successfull ==> successful
./src/sdp-utils.h:213: successfull ==> successful
./src/sdp-utils.h:292: defaukt ==> default
./src/sdp-utils.h:336: othwerwise ==> otherwise
./src/sdp-utils.h:375: othwerwise ==> otherwise
./src/ip-utils.h:117: inteface ==> interface
./src/ip-utils.h:128: inteface ==> interface
./src/ice.h:227: wether ==> weather, whether
./src/ice.h:230: wether ==> weather, whether
./src/ice.h:505: algorhitm ==> algorithm
./src/events.h:42: resetted ==> reset
```
etc.

**Comment by lminiero** [comment]
@tmatth that's interesting, I didn't know about that spell-checking functionality. I'll have a look at it myself later.

**Comment by Mahmo0odsalah** [comment]
@tmatth I wasn't specifically looking, I was just reading some code. However I see no harm in fixing those as well

**Comment by lminiero** [comment]
@Mahmo0odsalah will you fix all those yourself, then? In that case, I'll wait for the changes before a review/merge.

**Comment by lminiero** [comment]
I guess that's not going to happen, so I'll merge this, and have a look at codespell myself.

**Pull request merged**
