### PR TITLE
skip check/warn about local ip and no stun server if nat_1_1_mapping set

### PR DESCRIPTION
**Pull request by ploxiln**
a subjective cosmetic change, feel free to reject

(another idea is, if nat_1_1_mapping is set, check that to see if it is a local_ip. I'd be willing to make that change in this branch)

### CODE REVIEW

**Comment by lminiero** [comment]
The change makes sense: in that case, though, I agree that verifying whether ```nat_1_1_mapping``` is private would be a good idea, since we'd be skipping the test there. As an alternative, we might restore the ```if(stun_server == NULL && turn_server == NULL) {``` and use ```nat_1_1_mapping``` rather than che local IP when doing the "private IP" check.

**Comment by lminiero** [comment]
(or do both!)

**Comment by lminiero** [comment]
A simple way to do that could be to change the test we have like this:

	if(stun_server == NULL && turn_server == NULL) {
		/* No STUN and TURN server provided for Janus: make sure it isn't on a private address */
		gboolean private_address = FALSE;
		struct sockaddr_in addr;
		if(inet_pton(AF_INET, nat_1_1_mapping ? nat_1_1_mapping : local_ip, &addr) > 0) {
			unsigned short int ip[4];
			sscanf(nat_1_1_mapping ? nat_1_1_mapping : local_ip, "%hu.%hu.%hu.%hu", &ip[0], &ip[1], &ip[2], &ip[3]);
			if(ip[0] == 10) {
				/* Class A private address */
				private_address = TRUE;
			} else if(ip[0] == 172 && (ip[1] >= 16 && ip[1] <= 31)) {
				/* Class B private address */
				private_address = TRUE;
			} else if(ip[0] == 192 && ip[1] == 168) {
				/* Class C private address */
				private_address = TRUE;
			}
		}
		if(private_address) {
			JANUS_LOG(LOG_WARN, "Janus is deployed on a private address (%s) but you didn't specify any STUN server! Expect trouble if this is supposed to work over the internet and not just in a LAN...\n", nat_1_1_mapping ? nat_1_1_mapping : local_ip);
		}
	}

That is, basically replacing all occurrences of ```local_ip``` with ```nat_1_1_mapping ? nat_1_1_mapping : local_ip``` in the check, so that if ```nat_1_1_mapping``` was passed it is used for the local IP check instead.

**Comment by ploxiln** [comment]
I pushed up pretty much what you described.

**Comment by lminiero** [comment]
Cool, thanks! I'll merge this right away.

**Pull request merged**
