### PR TITLE
Update mvideoroomtest.js

### PR DESCRIPTION
**Pull request by henrylaxen**
Dear Lorenzo

I tried to explain everything in the mvideoroomtest-commented.txt file.  This is a refactoring of the current mvideoroomtest.js file to separate out the dom manipulation.  I hope you and your users will find it helpful.  If you have any questions, feel free to ask.
Best wishes,
Henry Laxen
[mvideoroomtest.zip](https://github.com/meetecho/janus-gateway/files/8503412/mvideoroomtest.zip)

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @henrylaxen! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Comment by lminiero** [comment]
To be honest, I can't review this, since it changes indentation, causing the _whole_ file to look different. Indentation must not be changed, as we use tabs, not spaces. If you fix that, I'll be happy to have a look. Thanks!

**Comment by henrylaxen** [comment]
Dear Lorenzo,
I used the tabify command in emacs to do the heavy lifting, and now my indentation matches yours as closely as possible.  This diffs are still very large, because so much code has been moved around.  Please let me know if there is anything else I can do to make things easier for you.
Best wishes,
Henry laxen

**Comment by lminiero** [comment]
Hey @henrylaxen, apologies for the very late feedback. I think this is a bit too much of a refactoring, especially considering it changes the code of a single demo, so I'm afraid I'll just close this. While we may fix a few things in the demos in the future (I already have a few things in mind I need to fix, expecially after the changes I made in #3003), I don't plan to completely revamp the way they work, since they're mostly meant as simple/dumb examples anyway, rather than anything more full fledged than that (and that's true for all demos, not just the multistream videoroom).

Thanks again for your contribution though!

**Pull request closed without merging**
