### PR TITLE
RTCRtpSender unavailable on old browsers

### PR DESCRIPTION
**Pull request by vahidov**

### CODE REVIEW

**Comment by lminiero** [comment]
How old are we talking about? :wink:  This should be available pretty much everywhere, now.

**Comment by vahidov** [comment]
https://caniuse.com/#search=RTCRtpSender - official stats
http://joxi.ru/GrqndjVckZRPam - own stat for 20 minutes

**Comment by lminiero** [comment]
I only see Firefox <=33 not supporting that: Firefox stable is 77 now. Not sure how to parse the second link you provided instead.

**Comment by vahidov** [comment]
@lminiero 
Chrome 49 doesn't support this. But it is last update version for windows xp. Yep, I understand, that is old system, but we have clients on it and this chrome is working fine for rest janus.js. 
And I don't see problem in one additional if. On line 343 you have same control for safari :-)

**Comment by lminiero** [comment]
The problem is we use senders and receivers a lot. The revived effort on multistream even more, almost exclusively so I believe. While a single conditional as provided here is fine, I honestly have no intention of adding tons of those to get a jurassic browser to work in the future.

**Comment by lminiero** [comment]
Merging this as it's a minor change. Please notice I won't refactor janus.js in case major changes are required though. Thanks!

**Pull request merged**
