### PR TITLE
[janus-pp-rec] Enhance timestamp assignment and add payload-type option to CLI.

### PR DESCRIPTION
**Pull request by atoppi**
In `janus-pp-rec` the timestamp assigned to each packet is a `uint64` that is used to monotonically order the packets in a recording.
This PR introduces a new algorithm in `janus-pp-rec` to assign packet timestamps in order to avoid erratic re-orderings that might lead to wrongly generated media files.

Since today that part of `janus-pp-rec` has relied on the  _"post reset trigger"_ mechanism to avoid messing media files (e.g. huge files) when particular orderings of timestamps were present.
This approach worked quite well so far but still it does not solve all corner cases. Furthermore it is in my opinion difficult to read, confusing to use and over-engineered.

This patch makes that mechanism more straightforward:
- remove the parameter `postreset-trigger` (you can not use it anymore in the CLI)
- instantly detects a timestamp reset (aka wrap-around) without the need of a trigger threshold
- use wrap-around aware checks to understand when a new timestamp is before or after the highest one

It has been tested with some mjrs containing special cases (timestamp reset in the first packets, out of order packets near the wrap around etc.) and it seemed to work as expected.

**UPDATE**: this PR also includes the changes proposed in #2412.

### CODE REVIEW

**Comment by lminiero** [comment]
Pinging @tgabi333 as I know he uses mjr files a lot.

**Comment by tgabi333** [comment]
Seems ok for me, thanks for letting me know

**Comment by tgabi333** [comment]
What about JANUS_PPREC_IGNOREFIRST?

**Comment by atoppi** [comment]
That part is unchanged.
I suspect that some of the issues that needed that setting could be solved by the new approach without using that parameter.

**Comment by lminiero** [comment]
I don't think the "ignore first" stuff is needed anymore with this fix.

**Comment by tgabi333** [comment]
@atoppi do you think that "ignore first" could be dropped out as well with this pull request?

**Comment by atoppi** [comment]
@tgabi333 not in this PR. 
Skipping the first packets of a mjr might still find a motivation in the future.

**Comment by lminiero** [comment]
Merging.

**Pull request merged**
