### PR TITLE
RTSP Content Base redirection

### PR DESCRIPTION
**Pull request by oliviermaignial**
Update RTSP uri if RTSP server provide a Content-Base header in describe request

### CODE REVIEW

**Comment by lminiero** [comment]
@oliviermaignial apologies for the very late reply! Been out of office the last week so couldn't look into this, and we just came back. Thanks for the patch! Can you fill in the form for our [CLA](https://cla.conf.meetecho.com/janus/) so that I can merge this?

**Comment by lminiero** [comment]
@oliviermaignial ping :wink:

**Comment by oliviermaignial** [comment]
Hello @lminiero, my company is being examinated your CLA, it still can takes few more days. I'll keep you posted when it's done.
Apologies for the delay

**Comment by lminiero** [comment]
Boy, they're really reading every single word in there... :wink:

**Comment by lminiero** [comment]
@oliviermaignial still no news?

**Comment by oliviermaignial** [comment]
Hello @lminiero,
The CLA has been examinated, it is OK, but there is still some internal questions about this contribution... Things seems more complex than I can figure out, but I'm still hopefull of winning this administrative game!
Some key peoples are in vacation this week. I'll try to get things done next week.

**Comment by oliviermaignial** [comment]
Hello @lminiero 
I can't obtain agreement of all peoples in this before at least few month. I close this PR, the patch should be re-submitted later.
Sorry for the inconvenience.

**Pull request closed without merging**
