### PR TITLE
Function to create reply with common parameters

### PR DESCRIPTION
**Pull request by andreasg123**
This adds the function `janus_create_reply` for the common pattern of creating a JSON reply object and setting the properties "janus", "session_id", and "transaction".

### CODE REVIEW

**Comment by andreasg123** [comment]
I rebased to the current refcount branch.

**Comment by lminiero** [comment]
Isn't `janus_create_message` more suited than `janus_create_reply`? We do send notifications as well from the core that are not a response to anything.

**Comment by andreasg123** [comment]
That makes sense.  Initially, I only used the new function for assignments to `reply` variables but I've found additional uses since.

**Comment by lminiero** [comment]
Looks good, tnx!

**Pull request merged**
