### PR TITLE
Fix occasional deadlock in VideoRoom (2) (credits to @mivuDing, fixes #1982)

### LINKED ISSUE #1982: a deadlock when janus_videoroom_destroy_session
Hi, I found a possible deadlock when "publisher A" enter janus_videoroom_destroy_session, and "subscriber B" subscribe "publisher A" at the same time. The detail step can be seen by the attach.
videoroom_deadlock
How to solve the problem?I want to unlock the sessions_mutex before destroy publisher, is it OK?
modify
Could you do me a favor? Thanks very much!

### PR DESCRIPTION
**Pull request by mp16**
Fix from the zip of @mivuDing

### CODE REVIEW

**Comment by lminiero** [comment]
I'll try to review this later; pinging @atoppi so that he can have a look too. In the meanwhile, if you can test and provide feedback on potential regressions that will help :+1:

**Comment by mp16** [comment]
Okay, I will test soon.

**Comment by mivuDing** [comment]
> Okay, I will test soon.
@mp16 Can you replicate the issue today?

**Comment by mp16** [comment]
It is during almost 24h that I am testing it in production (commit 0b9c46f04ae9964eff1ef7242c1fe94dc8be825e )

So far, so good, no regression and no deadlock (yet).

**Comment by mivuDing** [comment]
OK，I get it, thanks!

**Comment by lminiero** [comment]
> It is during almost 24h that I am testing it in production (commit [0b9c46f](https://github.com/meetecho/janus-gateway/commit/0b9c46f04ae9964eff1ef7242c1fe94dc8be825e) )
> 
> So far, so good, no regression and no deadlock (yet).

I assume you didn't get any deadlock in the meanwhile either, so I'll merge. Thanks to @mivuDing for the fix and @mp16 for validating it!

**Comment by mp16** [comment]
Yes. Since I test, 5 days ago, no more deadlock, with ~70 000 websockets connections (so sessions) per day on the test server. Thanks for the merge.

**Pull request merged**
