### PR TITLE
sip: manually handle re-INVITEs and reject them with 488

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
We could leave it as it was, but explicit is better than implicit!

Tested for incoming and outgoing. :+1:

**Comment by lminiero** [comment]
Makes sense, thanks for this. As a side note, please use tabs for indentation and not spaces.

**Comment by saghul** [comment]
damn, let me fix that real quick!

**Comment by saghul** [comment]
Should be kosher now. Sorry, I have my editor configured for The One True Indenting Model (R) and I sometimes forget to change it for Janus ;-)

**Comment by lminiero** [comment]
Thanks! Sorry for nit-picking :smile:

**Comment by lminiero** [comment]
Hey, I really _AM_ lazy! http://www.perlmonks.org/?node_id=158886

**Comment by saghul** [comment]
I'm not sure I can trust a Perl website! :sunglasses:

**Pull request merged**
