### PR TITLE
configurable screensharing framerate

### LINKED ISSUE #800: Janus Screensharing MaxFramerate of 3?
https://github.com/meetecho/janus-gateway/blob/master/html/janus.js#L1590

Why so low?  I think this should be 60.  There should also be a minimum frame-rate in here as well.  Ideally, this is configurable.

### PR DESCRIPTION
**Pull request by chadfurman**
closes #800

### CODE REVIEW

**Comment by lminiero** [comment]
Cool, thanks for this! Waiting for somebody to test this then :+1:

**Comment by chadfurman** [comment]
definitely needs testing.  Threw it together quick.  Though, I am testing the same code locally, so I'll report back :)

**Comment by lminiero** [comment]
PS: same changes need to be made to janus.nojquery.js too.

**Comment by chadfurman** [comment]
Oh, yup, forgot about that.  I'll verify it works first.

**Comment by chadfurman** [comment]
Ugh just broke indentation.  Will fix.

**Comment by chadfurman** [comment]
Fixed indent blugg, made changes to nojquery.

I was able to get a screenshare.  

Side note:  I did experience the same issue with audio: false.  And even though audio: false isn't in the explicit constraints in the demo code I mentioned, it seems the browser is dropping it into the constraints automatically.

That said, I have no idea how Alex was able to get audio into his screenshare.  I will follow up with him today.

**Comment by lminiero** [comment]
> Fixed indent blugg, made changes to nojquery.

Looks like the indentation issue is there instead, now... :wink:

**Comment by chadfurman** [comment]
oh, crap.  Well, to be fair, it is a different indentation issue...

I had accidentally re-indented the whole file...  that's fixed... *sigh*

**Comment by chadfurman** [comment]
fixed

**Comment by lminiero** [comment]
@chadfurman you may want to advertise the PR on the group to have more people test this, I'm sure there's interested users that don't know about this and might help get this merged sooner rather than later.

**Comment by chadfurman** [comment]
@lminiero done https://groups.google.com/forum/#!topic/meetecho-janus/fsDrrgzCL9E

**Comment by trankkilou** [comment]
sure I will test it

**Comment by trankkilou** [comment]
Ok I Tested it: 

I made a quick test on chrome but it seems to work fine.
I have the feeling it is more smooth (when dragging mouse) and the screen is less blur.
I think I have to test it longer on different device and different network.

**Comment by trankkilou** [comment]
Edit:

I made more test with a bigger screen and trying to up framerate to 60:
good news: works
bad news: no difference could be observe. when i drag a windows around my screen I have the same picture stuterring with framerate set up to 60 or without the option

**Comment by lminiero** [comment]
AFAIK Chrome developers are going to refactor the screensharing code, so I wouldn't expect it to perform that great at such a high framerate + resolution. Have you tried with Firefox too?

**Comment by chadfurman** [comment]
Mac has issues. Max 20 fps. Chrome on Windows and Linux should be smoother

**Comment by trankkilou** [comment]
ok good to know. it is true I have tried on a big resolution screen (imac 27")
on firefox i have this error

WebRTC error: Object { code: undefined, name: "NotAllowedError", message: "The request is not allowed by the u…" }  screensharingtest.js:172:16
	.callback/</janus<.success/<.onmessage/<.error https://janus.orange.com/screensharingtest.js:172:16
	callbackUserMedia https://janus.orange.com/janus.js:1524:8
	prepareWebrtc/< https://janus.orange.com/janus.js:1580:9
	getScreenMedia/<

**Comment by trankkilou** [comment]
Ok I have a windows laptop I could test on. but I should be able to notice a difference between 5fps (lorenzo code) and 20 fps right ?

**Comment by chadfurman** [comment]
5fps and 30fps for sure. Windows should be able to hit 50-60. 30 is where
your eye stops

**Comment by trankkilou** [comment]
I think human eye can't see any difference above 20fps  (that s why cinema movie started at 23.976fps) but maybe above you have a "better" feeeling of something smoother.

Anyway between 5fps and 20 fps the difference is hugh and clearly I didn't see my screen sharing at 20 fps: do you know where i should look ?

**Comment by chadfurman** [comment]
Make sure the back end is getting the value. Maybe your media prop isn't
coming through.

Might need to drop in a log...

**Comment by trankkilou** [comment]
In the browser console the parameters is well sent
in janus log, even in level 7, nothing about the framerate nor drop

what do you want me to send you as log ?

**Comment by lminiero** [comment]
This is a JavaScript only configuration, Janus has nothing to do with it...
As to Firefox, you have to whitelist the domain to get screensharing to work.

**Comment by chadfurman** [comment]
Sorry I meant make sure line 1473 has the right value for the frame rate.

**Comment by chadfurman** [comment]
And your saying on Windows you notice no difference if it's there or not?

**Comment by chadfurman** [comment]
Might be a JS cache issue, or maybe it isn't working?

**Comment by trankkilou** [comment]
I'm a terrible tester 🗡 :=)
I was not using the right janus.js !
So now it works and I can clearly notice the difference. I have tested at 30 fps (so 20fps I guess as it is on a mac) and it is REALLY smooth

I tried to get the value in the "media.screenshareFrameRate" variable in the console but I think I m too a newbee as i got this error : 

Uncaught ReferenceError: media is not defined

any idea ?

**Comment by chadfurman** [comment]
Yeah that var only exists at the time the function is executed. You'd have
to set a breakpoint.

Sounds like it's working though

**Comment by trankkilou** [comment]
ok I just log in the console and it is ok
Janus.debug(media.screenshareFrameRate);
->what I have set (60)

isVideoSendEnabled: Object {video: "screen", audio: false, videoRecv: false, screenshareFrameRate: 60}
janus.js:1474 60
janus.js:287 Long poll..

I tried on firefox and it works also

I can't notice difference between 30 and 60, maybe because of the OSX bug. I will try later on the windows

Now I will try to push up the resolution...

**Comment by trankkilou** [comment]
the resolution is set to max 2560*1440
now I m trying to up the bitrate
I create a constraint in janus.js and no warning message are coming (I can see my bitrate in the log) but I m quiet sure this is ignored so not the right way to do this

constraints = {
1590                                                                         audio: isAudioSendEnabled(media),
1591                                                                         bitrate: 2048000,
1592                                                                         video: {
1593                                                                                 mandatory: {
1594                                                                                         chromeMediaSource: 'desktop',
1595                                                                                         maxWidth: window.screen.width,
1596                                                                                         maxHeight: window.screen.height,
1597                                                                                         minFrameRate: media.screenshareFrameRate,
1598                                                                                         maxFrameRate: media.screenshareFrameRate,
1599                                                                                 },
1600                                                                                 optional: [
1601                                                                                         {googLeakyBucket: false},
1602                                                                                         {googTemporalLayeredScreencast: true}
1603                                                                                 ]
1604                                                                         }
1605                                                                 };
1606                                                                 constraints.video.mandatory.chromeMediaSourceId = event.data.sourceId;
1607                                                                 getScreenMedia(constraints, callback);


can u advice ?

**Comment by trankkilou** [comment]
update:

I did this in the videoroom.js but nothing change regarding bitrate
var publish = { "request": "configure", "audio": useAudio, "video": true, "bitrate": 4000000 };

**Comment by chadfurman** [comment]
Not sure, tbh. I didn't change anything there in this PR

**Comment by trankkilou** [comment]
it was a comment for lorenzo I guess :)
lorenzo has written several times he s using the videorrom for screensharing so I made this change in the videoroom.js. For what I read it is supposed to work but it s not working from my network counters pov.

**Comment by lminiero** [comment]
I don't see the point of discussing this here. Let's not mix problems, please.

**Comment by lminiero** [comment]
Looks like this is working, so merging, thanks! I'll take care of updating the docs to mention the new `screenshareFrameRate` option as well.

**Pull request merged**
