### PR TITLE
Fix deadlock in duktape plugin when calling pushevent from coroutines(async)

### PR DESCRIPTION
**Pull request by gabriel-munteanu**
How deadlock is happening:

1. janus_duktape.c:2282 janus_duktape_scheduler -> 2292 janus_mutex_lock(&duktape_mutex);	duk_get_global_string(duktape_ctx, "resumeScheduler");  call pushevent() from js
2. janus_duktape.c:486 janus_duktape_method_pushevent -> 570 janus_core->push_event
3. janus.c:2689 janus_plugin_push_event -> 2743 plugin->get_package()
4. janus_duktape.c:1675 -> 1679 janus_mutex_lock(&duktape_mutex);

With this fix I also fixed the type allowed for the 4th parameter of pushevent. It can be null and is not string :).

### CODE REVIEW

**Comment by gabriel-munteanu** [comment]
I translated for myself the videoroom plugin from Lua to JS and when I started to test I saw that when I was joining the room nothing is happening and after that the duktape was frozen. I started Janus with gdb, set a breakpoint janus_plugin_push_event and saw that when entering  plugin->get_package(),  I couldn't step after janus_mutex_lock(&duktape_mutex); .

Another solution to this problem is to call js function getPackage after the js plugin is loaded and store that string to be used after directly from C code.
I don't see any case where getPackage would need to return different results.

**Comment by lminiero** [comment]
> 3\. janus.c:2689 janus_plugin_push_event -> 2743 plugin->get_package()

Ok, I think here lies the problem. I'm pretty sure this is something I can replicate with the Lua plugin as well (I'll try in a minute). The `get_name`, `get_package`, etc., should only be invoked once (typically at startup), and not every time they're called, as those values are supposed to be immutable. Once we call them we can store the value and return that, which would fix the issue as there would be no mutex used anymore. I'll make some tests and keep you posted.

**Comment by lminiero** [comment]
@gabriel-munteanu just pushed the fix I was mentioning. Please let me know if it solves the deadlock you were receiving without the need for your patch (I verified it fixes the issue in the Lua plugin).

**Comment by gabriel-munteanu** [comment]
Yes, that commit solves that deadlock. 

I will come back later with another pull request for parameter restriction in janus_duktape_method_pushevent (2nd and 4th can be null an that is a different type than string).

**Comment by lminiero** [comment]
> Yes, that commit solves that deadlock.

Thanks for confirming!

> I will come back later with another pull request for parameter restriction in janus_duktape_method_pushevent (2nd and 4th can be null an that is a different type than string).

Any plan on when you'll submit? I was planning to tag a new version of Janus today (0.4.4), but I can wait for this other fix if you think it's important.

**Comment by lminiero** [comment]
Closing this PR in the meanwhile.

**Comment by gabriel-munteanu** [comment]
It is important but I'm a little bit busy with wedding preparations :D.
Please make you the following fixes in janus_duktape.c
L493: add this to condition && duk_get_type(ctx, 1) != DUK_TYPE_NULL
L503: add this to condition && duk_get_type(ctx, 3) != DUK_TYPE_NULL

You need this this because otherwise you will get: Duktape error: Error: Invalid argument (expected DUK_TYPE_STRING, got DUK_TYPE_NULL) .
duk_get_string() will know how to handle a null value.

You can check in the videoroom.lua that sometimes you call pushEvent with some parameters set to nil.

**Comment by lminiero** [comment]
> It is important but I'm a little bit busy with wedding preparations :D.

Wow, congratulations! Then what are you still doing here?! Get out! :smile: 

> Please make you the following fixes in janus_duktape.c
> L493: add this to condition && duk_get_type(ctx, 1) != DUK_TYPE_NULL
> L503: add this to condition && duk_get_type(ctx, 3) != DUK_TYPE_NULL

Thx, will do :+1: I'll refer to the changes you already made in this patch.

**Comment by lminiero** [comment]
Just applied your fix, thanks again!

**Pull request closed without merging**
