### PR TITLE
Fixed segmentation fault in pp-h264

### PR DESCRIPTION
**Pull request by thomas-apz**
I fixed on a segmentation fault in janus-pp-rec when using h264.

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks, but I don't understand what this fixes? Without the break, you get to a `tmp = tmp->next` (so now `tmp=NULL`)  followed by a `continue`. This is in a while loop that checks `while(*working && tmp != NULL) {`, and so we would break anyway. What am I missing?

**Comment by thomas-apz** [comment]
Hi Lorenzo, 

Without this break the continue goes directly to the while(1) and the
next instruction is if(tmp->drop) (where I stumbled on a SEGV). 

Am I wrong ? 

Since I added the fix, I encountered no SEGV. 

Thomas 

On 20.07.2018 14:34, Lorenzo Miniero wrote:

> Thanks, but I don't understand what this fixes? Without the break, you get to a tmp = tmp->next (so now tmp=NULL) followed by a continue. This is in a while loop that checks while(*working && tmp != NULL) {, and so we would break anyway. What am I missing? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [1], or mute the thread [2].

 

Links:
------
[1]
https://github.com/meetecho/janus-gateway/pull/1305#issuecomment-406587537
[2]

**Comment by lminiero** [comment]
Ooh, you're right, I missed the inner while... I shouldn't look at code so early in the morning :smile: 
Can you fill in the form in our [CLA](https://cla.conf.meetecho.com/janus/) so that we can merge this?

**Comment by thomas-apz** [comment]
It's done. 

On 20.07.2018 14:51, Lorenzo Miniero wrote:

> Ooh, you're right, I missed the inner while... I shouldn't look at code so early in the morning 😄
> Can you fill in the form in our CLA [1] so that we can merge this? 
> 
> --
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub [2], or mute the thread [3].

 

Links:
------
[1] https://cla.conf.meetecho.com/janus/
[2]
https://github.com/meetecho/janus-gateway/pull/1305#issuecomment-406591450
[3]

**Comment by lminiero** [comment]
Thanks, merging then :+1:

**Comment by tgabi333** [comment]
:+1:

**Pull request merged**
