### PR TITLE
Lsolak add video orientation extension

### PR DESCRIPTION
**Pull request by lejlasolak**

### CODE REVIEW

**Comment by lminiero** [comment]
Sorry for the late response, going back to the office tomorrow and I'll review.

**Comment by lejlasolak** [comment]
> Sorry for the late response, going back to the office tomorrow and I'll review.

Hi, any update?

**Comment by lminiero** [comment]
I didn't have time to look at the pull request, sorry. Hopefully I'll do that later this week, or the next.

**Comment by lminiero** [comment]
This looks much better than the approach originally proposed, thanks :+1: 
To make this complete, though, it should address other the audio-level extension too, as it's part of the structure as well and so may get "lost in translation" just like the video-orientation one. Once that part is done, I think this is fine to merge. I'll take care of applying the same fix to the NoSIP plugin as well, which would suffer from the same problem otherwise.

As a side note, please fill in the form and sign our [CLA](https://cla.conf.meetecho.com/janus/) which is a prerequisite for merging.

**Comment by lminiero** [comment]
Oh, one more thing: this should based on the `plugins-media` branch, not `transport-cc`: the latter is based on the former, but it's the former that needs the fix, since that's where we refactored RTP extensions. Once this is merged in `plugins-media`, I'll merge the changes in `transport-cc` too.

Anyway, I think I can do this myself using the `Edit` button, so nothing you need to worry about.

**Comment by lminiero** [comment]
Thanks for the quick fixes! Looks good to me :+1: 
As soon as the CLA is signed, I'll merge.

**Comment by lejlasolak** [comment]
> Thanks for the quick fixes! Looks good to me 👍
> As soon as the CLA is signed, I'll merge.

Done

**Comment by lminiero** [comment]
Mh, looks like I can't just rebase from GitHub, since otherwise it pulls in fixes from `transport-cc` as well, and not just the additions you made... Can you prepare a new PR, based on `plugins-media`, with just the `janus_sip.c` changes? Thanks!

**Comment by lejlasolak** [comment]
I created pull request on plugins-media branch
https://github.com/meetecho/janus-gateway/pull/1928

**Comment by lminiero** [comment]
Thanks! Closing this one, then.

**Pull request closed without merging**
