### PR TITLE
Autogenerate DTLS cert/key if not specified

### PR DESCRIPTION
**Pull request by saghul**
The ultimate goal here is to have Janus working without any configuration. This brings us one step closer!

/cc @lminiero

### CODE REVIEW

**Comment by lminiero** [comment]
This looks useful, thanks for working on this!

I'd make it much more explicit when you're generating new certificates, though. Folks may have improperly configured their own certificates and end up using random ones without being aware of it otherwise. Maybe a `LOG_WARN` in the `if (!server_pem && !server_key) {` check that leads to `janus_dtls_generate_keys`?

**Comment by lminiero** [comment]
Or maybe a command line option that says "autogenerate" that will override the check for existing ones? Not sure what the best approach is.

**Comment by saghul** [comment]
I thought of that. My take is the following: if you specify either but not both we give an error. If you give both we load them, and if you give neither, then we generate them.

So the only way to generate them by mistake would be to leave the options commented out.

Alternatively, we cold have a special token `<auto>` which must be set in order to generate them, but it needs to be set for both at the same time. Thoughts?

**Comment by saghul** [comment]
> Maybe a LOG_WARN in the if (!server_pem && !server_key) { check that leads to janus_dtls_generate_keys?

I'd be ok with that to avoid further config complications. Remember my ultimate goal is to have zero configuration 😎

**Comment by lminiero** [comment]
I think a LOG_WARN is enough then!

**Comment by saghul** [comment]
Done!

**Comment by lminiero** [comment]
Cool, tnx! Let me do a quick check and I'll merge :+1:

**Comment by lminiero** [comment]
Looks good, merging!

**Pull request merged**
