### PR TITLE
a couple of memory leaks fixes (spotted by valgrind)

### PR DESCRIPTION
**Pull request by emmanuelriou**
These are a couple of mem leaks spotted by valgrind. To be continued as we are just starting to use valgrind with janus.

Cheers,

-- Emmanuel

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks, let me know when this is done so that I can look into the changes :+1:

**Comment by mirkobrankovic** [comment]
Hi @emmanuelriou ,
Have you encountered leaks in websocket transport and audiobridge like this:
`==18375== 16 bytes in 1 blocks are definitely lost in loss record 216 of 793
==18375==    at 0x4C2EB6B: malloc (vg_replace_malloc.c:299)
==18375==    by 0x6F92ADE: __nss_database_lookup (in /usr/lib64/libc-2.25.so)
==18375==    by 0x6F94CCB: __nss_passwd_lookup2 (in /usr/lib64/libc-2.25.so)
==18375==    by 0x6F319F2: getpwuid_r@@GLIBC_2.2.5 (in /usr/lib64/libc-2.25.so)
==18375==    by 0x6F30FA7: getpwuid (in /usr/lib64/libc-2.25.so)
==18375==    by 0x1E3C6F6D: lws_plat_drop_app_privileges (in /usr/lib64/libwebsockets.so.10)
==18375==    by 0x1E3BA5CE: lws_finalize_startup (in /usr/lib64/libwebsockets.so.10)
==18375==    by 0x1E3BFC3D: lws_protocol_init (in /usr/lib64/libwebsockets.so.10)
==18375==    by 0x1E3BB66A: lws_service_fd_tsi (in /usr/lib64/libwebsockets.so.10)
==18375==    by 0x1E3C6D8A: _lws_plat_service_tsi (in /usr/lib64/libwebsockets.so.10)
==18375==    by 0x1E1A7DC6: janus_websockets_thread (janus_websockets.c:845)
==18375==    by 0x56E4535: ??? (in /usr/lib64/libglib-2.0.so.0.5200.3)

==18375== 216 bytes in 9 blocks are definitely lost in loss record 739 of 793
==18375==    at 0x4C2EB6B: malloc (vg_replace_malloc.c:299)
==18375==    by 0x56C2A38: g_malloc (in /usr/lib64/libglib-2.0.so.0.5200.3)
==18375==    by 0x56DA575: g_slice_alloc (in /usr/lib64/libglib-2.0.so.0.5200.3)
==18375==    by 0x56DAA08: g_slice_alloc0 (in /usr/lib64/libglib-2.0.so.0.5200.3)
==18375==    by 0x56B8BB8: ??? (in /usr/lib64/libglib-2.0.so.0.5200.3)
==18375==    by 0x13FDABAB: janus_audiobridge_incoming_rtp.part.5 (janus_audiobridge.c:2519)
==18375==    by 0x431A40: janus_ice_cb_nice_recv (ice.c:2073)
==18375==    by 0x4E462CF: ??? (in /usr/lib64/libnice.so.10.6.2)
==18375==    by 0x4E5030E: ??? (in /usr/lib64/libnice.so.10.6.2)
==18375==    by 0x5100120: ??? (in /usr/lib64/libgio-2.0.so.0.5200.3)
==18375==    by 0x56BD246: g_main_context_dispatch (in /usr/lib64/libglib-2.0.so.0.5200.3)
==18375==    by 0x56BD5E7: ??? (in /usr/lib64/libglib-2.0.so.0.5200.3)
`
Thanks

**Comment by emmanuelriou** [comment]
Hi @mirkobrankovic 
I am only using rabbitmq as transport mode, with our own plugin, so I didn"t have a chance to test websocket transport and audiobridge plugin. Anyway, if you spotted them out, it is probably worth a patch.

-- Emmanuel.

**Comment by lminiero** [comment]
Notice that some glib related leaks are actually not leaks at all, due to the memory management that glib does and that valgrind may not correctly track.

**Comment by lminiero** [comment]
Closing as this seems outdated: the nacks list management for instance has changed quite a much, in the meanwhile, and I definitely don't see any leak there right now.

**Pull request closed without merging**
