### PR TITLE
json validation helpers - use for all plugins

### PR DESCRIPTION
**Pull request by ploxiln**
also add `JANUS_CHECK_SECRET()` and `JANUS_CHECK_PIN()` helpers

this is a follow-up of #517 (the rest of #494)

### CODE REVIEW

**Comment by lminiero** [comment]
Wow, that was much faster than a day! :smile:  I'll check this tomorrow in the morning with fresh eyes and in case everything's fine I'll merge right away.
Thanks!

**Comment by lminiero** [comment]
Looks fine to me. Just as a side note, since `JANUS_CHECK_SECRET` and `JANUS_CHECK_PIN` are basically the same, apart from the name of the element to check, why not make it a generically appliable method that has the element name to verify as part of its signature?

**Comment by ploxiln** [comment]
yeah looks like those could be combined, I'll add a commit for that

**Comment by lminiero** [comment]
Thanks!

**Comment by ploxiln** [comment]
updated

**Comment by lminiero** [comment]
Thanks! I'll do a quick further revision check and then merge.

**Pull request merged**
