### PR TITLE
core: replace std{in,out,err} with /dev/null when daemonizing

### PR DESCRIPTION
**Pull request by saghul**

### CODE REVIEW

**Comment by saghul** [comment]
(sorry about the bonus whitespace fix, editors! I can remove that if you want)

**Comment by lminiero** [comment]
s/stout/stdout

**Comment by saghul** [comment]
Fixed.

**Comment by lminiero** [comment]
Ok, waiting for feedback from #406 before merging. In the meanwhile, I guess I should probable disable the automatic libnice logging when debug level is 7: we have a separate option for that, and it's confusing.

**Comment by saghul** [comment]
As a general rule, replacing fds 0-2 with /dev/null when daemonizing is A Good Idea, since some libraries could expect them to point to the real thing.

**Comment by lminiero** [comment]
:+1:

**Comment by lminiero** [comment]
I eventually integrated your fix in another commit that fixes a different issue I encountered: https://github.com/meetecho/janus-gateway/commit/365b8c95171537d656138fe21462e3af33d05e5a
So we can close this one, thanks for the heads up!

**Comment by saghul** [comment]
IMHO that fix is not correct. First, it closes the descriptors anyway, which it shouldn't since fdreopen does that automagically, but more importantly, the daemonizing logic is now scattered around, which makes it harder to follow, and there is no reason to move the logic to the log initialization routine. Reopening stdout actually makes the rest of the softwre transparent, since there exists some stdout, it just happens to point to /dev/null.

**Comment by lminiero** [comment]
> First, it closes the descriptors anyway

Sorry, copy/paste error, will fix this...

> there is no reason to move the logic to the log initialization routine

Only the output redirection is moved, nothing else, and for a specific reason. I was getting errors daemonizing, but nothing was printed, as the logger init uses ```g_print``` and the console output had already been closed, and so I had no idea what was wrong. Disabling that I found out I was doing something wrong with the log paths and could fix that. That's why I decided to only take care of the console output when initializing the logger, which IMHO makes sense as that's the whole point of the logger anyway.

**Comment by saghul** [comment]
Honest question: why not use syslog, and have syslog divert to a file instead of reinventing that?

**Comment by lminiero** [comment]
syslog has been an option I considered about a month ago, but eventually I gave it up for a few reasons, namely debugging level collisions that would have forced me to update the whole code (LOG_WARNING, LOG_INFO, etc. are used by syslog too) and the fact that it logs to somewhere you cannot choose (e.g., journald in Fedora or /var/log/messages on some other systems, rather than a log file of your choice as we wanted).

**Comment by saghul** [comment]
> namely debugging level collisions that would have forced me to update the whole code (LOG_WARNING, LOG_INFO, etc. are used by syslog too)

Prefixing them with JANUS_ would solve it easily.


> and the fact that it logs to somewhere you cannot choose (e.g., journald in Fedora or /var/log/messages on some other systems, rather than a log file of your choice as we wanted).

Janus could have a configurable log local and them have the syslog daemon divert those to a file, this is common practice.

**Comment by lminiero** [comment]
> Prefixing them with JANUS_ would solve it easily

See rewriting the whole code, as they're used everywhere :smile: 

> Janus could have a configurable log local and them have the syslog daemon divert those to a file, this is common practice.

From what I read around this was not so easy, mostly because of the different backend systems that different distros use (e.g., journald vs rsyslog vs whatever) and that would have needed different setups. Not sure this can be done on Fedora, for instance.

Anyway, I think Pierce and Jay did an excellent job on the logger, and I'm happy with the result.

**Comment by saghul** [comment]
> From what I read around this was not so easy, mostly because of the different backend systems that different distros use (e.g., journald vs rsyslog vs whatever) and that would have needed different setups.

This is no different from using syslog-ng vs rsyslog, each syslog software has its own configuration, but configuring the log local is standard.

> Not sure this can be done on Fedora, for instance.

Sure it does. Fedora uses Systemd, so one coud launch Janus and forward its output to a given file from the unit file.

> Anyway, I think Pierce and Jay did an excellent job on the logger, and I'm happy with the result.

Oh, I never implied otherwise!

**Pull request closed without merging**
