### PR TITLE
devicetest: unused var removed

### PR DESCRIPTION
**Pull request by RSATom**
It looks like someone just forgot remove it on refactoring...

### CODE REVIEW

**Comment by lminiero** [comment]
Why do you think it's unused? We use to only perform that action the very first time.

**Comment by RSATom** [comment]
It doesn't matter true it or false `restartCapture()` will be called...

**Comment by lminiero** [comment]
Ah I get what you mean, now: we do a `restartCapture` anyway.

**Comment by lminiero** [comment]
Looks like it's because of 1cae99dd23644695cdac41d6671f3a1093a7be27, which is where we changed the behaviour of the demo to renegotiate rather than hangup and create the session again. Previously, if `firstTime` was `false` we would hangup and then recreate the PR a couple of seconds later. I agree it's not needed anymore.

It's still a bit silly to renegotiate, though: it would make more sense to use `replaceTrack` instead (which we don't support in `janus.js`, though, and so would need to be done manually).

**Comment by RSATom** [comment]
Hm... I've found this when was investigating issue with change source cam with [iosrtc](https://github.com/cordova-rtc/cordova-plugin-iosrtc) on iOS device (it just fails). Maybe it's really related to missing `replaceTrack` in janus.js - I'll investigate. Thank you for good point.

**Comment by lminiero** [comment]
To clarify, `janus.js` will use `replaceTrack` internally, but it will renegotiate as well: there's currently no way to only replace the track and avoid the renegotiation.

**Pull request merged**
