### PR TITLE
rabbitmq exchange type as config value

### PR DESCRIPTION
**Pull request by voicenter**
By the feature request mention in #2023

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! I'll notify the people in that issue about this effort so that they can test it.

**Comment by pitkonst** [comment]
Looks fine for me. There is FIXME comment in both files (line 95 and 112), witch could be removed.

**Comment by voicenter** [comment]
@pitkonst , let me know if any more change needed,
I didn't add the parameter to the config file as it is optional, 
let me know what is the project  policy about it,
should I have it in the doc and sample config files...
thanks again ...
Shlomi

**Comment by pitkonst** [comment]
About project policies we better ask @lminiero

**Comment by lminiero** [comment]
A commented value in both config files (just to let people know it exists) would definitely help. You can use the existing lines as a template for the new property. I also noticed your patch has a lot of empty lines in between code snippets, so please just keep one for those (even though it's an easy nit I can fix myself after merging).

**Comment by lminiero** [comment]
Thanks for the quick fixes! This seems good to merge for me: unless I see any objection on the original issue, I'll merge tomorrow morning :+1:

**Comment by lminiero** [comment]
I don't see any objection, so I'll merge, thanks again! :+1:

**Pull request merged**
