### PR TITLE
Fix Janus.isWebrtcSupported

### PR DESCRIPTION
**Pull request by leonklingele**
Previous function did not work as expected.

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! You're right, I meant to change that (uncompliant browsers would have those undefined, not null) and always forgot to do that.

Before I can merge this, can you sign our [CLA](https://cla.conf.meetecho.com/janus/)?

**Comment by leonklingele** [comment]
Done. :)

**Comment by lminiero** [comment]
> Done. :)

Can you try again? I still don't see it, might be a hiccup in our server :open_mouth: 
You need to authenticate via github, and then compile the data at the end of the page.

Thanks!

**Comment by leonklingele** [comment]
I see, sorry. Missed to fill out the form at the confirmation page.

**Comment by lminiero** [comment]
Thanks, merging!

**Pull request merged**
