### PR TITLE
html: update webrtc-adapter to 7.7.0

### PR DESCRIPTION
**Pull request by tmatth**
N.B. This project is in maintenance mode.

### CODE REVIEW

**Comment by lminiero** [comment]
IIRC I didn't bump the version as they dropped support for some browser versions that some people still needed (e.g., older versions of Firefox that were still in some repos), but not 100% sure. Have you checked if demos still work as expected?

**Comment by fippo** [comment]
the versions no longer supported by /them/ were at least two years out of date back in 2018 so they're now four years out of date, no?

**Comment by lminiero** [comment]
Oh it's very likely that what I'm referring to is something that _may_ have made sense years ago, and very little now. I was just trying to justify my laziness 😁

**Comment by lminiero** [comment]
Merging :v:

**Comment by lminiero** [comment]
Mh I guess I should have tested this instead of blindly trusting it to work... there's no 7.7.0 on cdnjs, it stops at 7.4.0
https://groups.google.com/g/meetecho-janus/c/Hh2lBAFLp8s
https://cdnjs.com/libraries/webrtc-adapter/7.4.0

**Comment by fippo** [comment]
I wonder why that is... haven't changed anything about how stuff gets published at that point.

**Comment by tmatth** [comment]
> Mh I guess I should have tested this instead of blindly trusting it to work... there's no 7.7.0 on cdnjs, it stops at 7.4.0
> https://groups.google.com/g/meetecho-janus/c/Hh2lBAFLp8s
> https://cdnjs.com/libraries/webrtc-adapter/7.4.0

Sorry for missing this, I'd test unpkg.com (https://unpkg.com/webrtc-adapter@7.7.0/out/adapter_no_edge.js ) but neglected to test cdnjs.

**Pull request merged**
