### PR TITLE
Ext orientation video recording sip

### PR DESCRIPTION
**Pull request by adnanel**
Similar to what was done in https://github.com/meetecho/janus-gateway/pull/2527

We add the orientation extension id in the MJR header so it can be read & applied when processing the video afterwards.

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @adnanel! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Review by lminiero — COMMENTED** [review]
Thanks! But indentation is broken. We use tabs, not spaces.
Besides, you don't really need the checks, something like this willbe be enough:

    if(session->media.video_orientation_extension_id > 0)
        janus_recorder_add_extmap(session->vrc, session->media.video_orientation_extension_id, JANUS_RTP_EXTMAP_VIDEO_ORIENTATION));

**Comment by adnanel** [comment]
Adjusted to look like the rest of the code, sorry. Please take a new look when you find the time. Thanks!

**Comment by lminiero** [comment]
Looks good, thanks! Merging :+1:

**Pull request merged**
