### PR TITLE
Update janus.d.ts

### PR DESCRIPTION
**Pull request by caiiiycuk**
Function `getBitrate()` actually returns string, like `699 kbits/sec`

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @caiiiycuk! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Comment by lminiero** [comment]
Thanks! As soon as you sign the CLA, we'll merge this.

**Comment by caiiiycuk** [comment]
Signed

**Comment by lminiero** [comment]
Thanks, merging :+1:

**Pull request merged**
