### PR TITLE
Remove unused "srtp_mutex".

### PR DESCRIPTION
**Pull request by fancycode**

### CODE REVIEW

**Comment by lminiero** [comment]
Not really sure what this was for: I think it was probably from a long time ago, when we could still end up trying to SRTP encrypt from different threads, which is something that will never happen in the current code. Thanks for spotting this and fixing it!

**Comment by fancycode** [comment]
You're right about SSL/SRTP.

#1213 looks similar, but it's `janus_ice_thread` racing with `janus_ice_send_thread`, where my crash was with SCTP (and BoringSSL instead of OpenSSL). But yes, using a SSL context from different threads will lead to strange errors.

**Comment by lminiero** [comment]
That shouldn't be the case, though, as we're explicitly handling the thread safeness for OpenSSL in dtls.c: https://github.com/meetecho/janus-gateway/blob/master/dtls.c#L108

**Comment by fancycode** [comment]
Hmm, according to the OpenSSL documentation it's *not* safe to use the same SSL context from different threads: https://www.openssl.org/docs/man1.0.2/crypto/threads.html

> Note that OpenSSL is not completely thread-safe, and unfortunately not all global resources have the necessary locks. Further, the thread-safety does not extend to things like multiple threads using the same SSL object at the same time.

**Comment by lminiero** [comment]
Which is why we use the `CRYPTO_THREADID_set_callback` stuff, which AFAIK is supposed to take care of exactly that. We did have crashes due to race conditions in the past (the commented block I linked to in my previous comment has more info) that this approach fixed.

**Comment by lminiero** [comment]
This might be one more reason to start working on using the libnice loop thread for outgoing media too, in order to get rid of the send thread we have now. I have been thinking about this these last few days, but still haven't investigated how complicated or messy it would be with the glib event loop. I already worked on something like this when prototyping my own ICE stack (something I never got to submit here, actually) but that used libevent2.

**Comment by fancycode** [comment]
> Although I guess you mean that this may not be enough, as some structures may not have locks in place, and so would never be locked even in that case?

Yes, e.g. `SSL_write` / `SSL_shutdown` don't do any locking:
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/ssl/ssl_lib.c#L1043
https://github.com/openssl/openssl/blob/OpenSSL_1_0_2-stable/ssl/ssl_lib.c#L1058

> This might be one more reason to start working on using the libnice loop thread for outgoing media too, in order to get rid of the send thread we have now. 

Sounds like a good idea.

**Pull request merged**
