### PR TITLE
Some fixes for the SIP gateway plugin

### PR DESCRIPTION
**Pull request by saghul**
I have some more in the works, I thought I'd send them in small PRs.

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks for working on this!

The string dupliation for tags in particular is something I was indeed interested in, as I do recall looking for info in the Sofia-SIP documentation about whether or not this was needed and I couldn't find anything. Since at the time there were some segfaults in the SIP plugin, I assumed that in part they could be blamed on strings that were not duped before passing them to the stack. Can you confirm this is unneeded?

**Comment by saghul** [comment]
I also struggled to find documentation about it, but when a constant is passed nobody tries to free it or it would explode. Also some testing and digging in the FreeSWITCH code strongly suggest is not really necessary :-)

**Comment by lminiero** [comment]
Thanks for the clarification, merging then!

**Comment by saghul** [comment]
Fantastic, thanks!

**Pull request merged**
