### PR TITLE
Fix janus_ducktape plugin

### PR DESCRIPTION
**Pull request by gabriel-munteanu**
Remove input js file size limit

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! But the indentation is all broken: please use tabs and not whitespaces, as per the guidelines. There's an `.editorconfig` file in the repo if your IDE supports it.

**Comment by lminiero** [comment]
PS: please fill in our [CLA](https://cla.conf.meetecho.com/janus/) form as well, so that we can merge this when ready.

**Comment by gabriel-munteanu** [comment]
Fixed indentation and signed the CLA.

**Comment by lminiero** [comment]
Thanks, merging then! Notice I'll replace the `malloc/free` with `g_malloc/g_free`, mostly for code consistency (it's what we use in all the rest of the code).

**Comment by gabriel-munteanu** [comment]
No problem. Thank you!

**Pull request merged**
