### PR TITLE
Mutex janus_ice_setup_local call (fix for  #1710)

### PR DESCRIPTION
**Pull request by Bug-Fairy**
Should fix all the issues relating to #1710. Didn't notice any side effects from my own testing.

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! Please fill in the form and sign our [CLA](https://cla.conf.meetecho.com/janus/), before we can merge it.

**Comment by Bug-Fairy** [comment]
Done. Sorry for the delay, was away from civilization for a week.

**Comment by atoppi** [comment]
lgtm, waiting for @lminiero for the final approval.

**Comment by lminiero** [comment]
Apologies, I've just returned from my vacation. I'll have a look either today or on Monday. Thanks!

**Comment by lminiero** [comment]
Looks good here too! Thanks for the fix, merging!

**Pull request merged**
