### PR TITLE
Fix getting min/max values in janus_rtp_header_extenstion_parse_playo…

### PR DESCRIPTION
**Pull request by hijaq**
…ut_delay

### CODE REVIEW

**Comment by lminiero** [comment]
Good catch! Could you sign our [CLA](https://cla.conf.meetecho.com/janus/) before I can merge this? Considering it's a tiny change, I can also incorporate it myself if you'd rather do that.

**Comment by hijaq** [comment]
Probably it'll take some time to fill "Corporate Contributor Information" part, so you can incorporate it yourself =)

**Comment by hijaq** [comment]
signed it

**Comment by lminiero** [comment]
Thanks, merging directly then!

**Pull request merged**
