### PR TITLE
Fixed documentation in plugin videoroom

### PR DESCRIPTION
**Pull request by Hajto**
Title is self explanatory, fixed and repetition.

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @Hajto! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Comment by lminiero** [comment]
@Hajto apologies, I must have missed the notification for this PR. Can you sign the CLA so this can be merged? Thanks!

**Comment by Hajto** [comment]
I can't sign the CLA, I would really appreciate if you made this change yourself and close this or. Best wishes.

**Comment by atoppi** [comment]
Done, thanks @Hajto .

**Pull request closed without merging**
