### PR TITLE
Notify codecs on stream published/forwarded events

### PR DESCRIPTION
**Pull request by zevarito**
Notify VideoRoom publisher AV codecs for **published** and **rtp_forward** events.

### CODE REVIEW

**Comment by januscla** [comment]
Thanks for your contribution, @zevarito! Please make sure you sign our [CLA](https://cla.conf.meetecho.com/janus), as it's a required step before we can merge this.

**Comment by zevarito** [comment]
Please let me know if this change requires tests & documentation.

**Comment by lminiero** [comment]
Looks good, thanks! We can't merge until you sign the CLA, though. Please let us know when that's done.

**Comment by zevarito** [comment]
@lminiero just signed, thanks.

**Comment by lminiero** [comment]
Ack, merging :+1:

**Comment by lminiero** [comment]
Group please. But I don't think we'll enforce any templating. Each plugin must be free to implement whatever they want the way they want, as long as they use JSON and use the right internal callbacks. The fact most plugins seem to have a similar API is only a coincidence, and a consequence of the fact I happened to write them all, but the simple fact that each plugin could implement a completely different logic (and satisfy different requirements) from other plugins means any templating beyond the rules we already have now would be impossible.

**Comment by zevarito** [comment]
Are you saying that add `show` request to VideoRoom plugin *only* is feasible?
Would be also accepted a function say `json_object_room` that wraps this code[0] for example?
Sure, I'll post next time into the group, I wasn't sure since most of time I've seen request for help in how to use janus instead of code questions/propositions.

[0] https://github.com/meetecho/janus-gateway/blob/master/plugins/janus_videoroom.c#L3622-L3656

**Pull request merged**
