### PR TITLE
janus_ice_send_thread(): use g_async_queue_timeout_pop()

### PR DESCRIPTION
**Pull request by ploxiln**
Instead of g_usleep() for 10ms when queue is empty, wait up to 500ms for a message on the queue. 500ms timeout is needed so receive silence over 1 second period is still detected. (It might end up not checking until almost 1.5 seconds since the previous check, but I think that's OK.)

No rush to merge this, I've only done a bit of testing so far, and this will go out for much more testing on some of our servers in a few days.

### CODE REVIEW

**Comment by ploxiln** [comment]
I've been running this for a while, and I've seen a noticeable improvement in context switching. Just for fun, here are some graphs.

janus31 is not using this patch:
interrupts-day-janus31

janus34 is using this:
interrupts-day-janus34

(As Lorenzo knows) we have a videoroom like plugin with "captures" and "viewers", and the below graph shows that there are a comparable number of clients of each type connected to these two servers over this period of time:
screen shot 2015-12-27 at 17 43 24

**Comment by lminiero** [comment]
That's a very welcome improvement, thanks for working on this!
I'm away from my working pc now (and have been away from home these last few days, so sorry for this late response), I'll merge this into the main branch as soon as I get back to it.

**Comment by ploxiln** [comment]
I was just posting stuff up while it's fresh. Enjoy your vacation :)

**Comment by lminiero** [comment]
> 500ms timeout is needed so receive silence over 1 second period is still detected. (It might end up not checking until almost 1.5 seconds since the previous check, but I think that's OK.)

How does it go from 500ms to only wake up 1.5s later? Is ```g_async_queue_timeout_pop``` so unreliable/vague?

**Comment by ploxiln** [comment]
I mean, if it wakes up 999ms after it last checked for "no data", it won't check. Then, it could be another 500ms until it checks again.

(but in the typical case it'll wake up 33ms or so later when the next packet is sent)

**Comment by lminiero** [comment]
Ah, got it: is this why you added the ```g_usleep(100000);``` if no message was received after 500ms? To make it more likely the >1s check triggers sooner rather than later? Since the patch is relying on signals, isn't it better to remove the sleep entirely, and just let the check go through and maybe fail (I guess it's really not important if you no-media event is sent after 1s or 1.5s of inactivity), in case you start receiving packets immediately after that, and that you'd only handle 100ms later?

**Comment by ploxiln** [comment]
The `g_usleep(100000)` is just for the case that the g_async_queue is itself NULL, which I'd think should be impossible, but it's a case that the original code handled. So it avoids busy looping in his possibly impossible situation, and it avoids me having to figure out if it's really impossible or not, for this not-directly-related change :)

**Comment by lminiero** [comment]
You're right, sorry... it's in the ```if(handle->queued_packets != NULL) {``` else, not in the "packet is NULL" one... I should really stop looking at code during the holidays! :smile:

**Comment by lminiero** [comment]
Finally found some time to look into this and it seems fine, thanks, merging!

**Pull request merged**
