### PR TITLE
Allow negotiation of AV1 and H265

### PR DESCRIPTION
**Pull request by lminiero**
This patch lays the foundation for AV1 and H.265 support in Janus, as the former will soon land in Chrome thanks to CoSMo's efforts, and the latter has apparently landed already in Safari.

Notice that this doesn't mean these codecs are _really_ supported already... we now only allow them to be negotiated, and plugins are aware of them, but since I currently have no idea how they're packetized, there's important stuff missing, like:

* the ability to detect a keyframe in either codec (the related functions are placeholder, right now)
* support for the new RTP extension AV1 makes use of
* the ability to post-process an AV1 or H.265 .mjr recording to a playable file
* whether or not simulcast is available when those codecs are used (no idea)

That's unlikely to change any time soon, since I don't have access to neither a Mac (I'm locked down at home with no one to borrow one from), nor to an AV1-compliant Chrome (but thanks to @agouaillard that [should change soon](https://github.com/CoSMoSoftware/libwebrtc-AV1/wiki)), so I have no way to play with these things myself. And yes, I know there are some specifications out there, but I'd much rather tinker with actual packets right now than spend hours I don't have reading abstract documents with nothing to validate them.

If you're willing to start playing with this, I'll welcome .mjr recordings and unencrypted .pcap captures (maybe obtained via the Admin API feature) to see what those packets actually look like, which may help speed the process. Even in that case, though, no promise: I'm awfully busy so I'll just have a look when I have some time to breathe. If you're particularly interested in prioritizing either, you may want to consider sponsoring the development.

Feedback welcome!

### CODE REVIEW

**Comment by lminiero** [comment]
FYI, a quick way to test this is using the default `echotest.html` demo, since it supports a `vcodec` query string argument to force a specific video codec to be used. As such, opening `echotest.html?vcodec=av1` will force AV1 negotiation, and `echotest.html?vcodec=h265` will do the same for H265. Hopefully negotiation at the very least should work, and media should too.

**Comment by ibc** [comment]
> I'm locked down at home with no one to borrow one from  so I have no way to play with these things myself

depresion-688731

**Comment by trankkilou** [comment]
Hi,

it works !

here the sdp of janus

https://pastebin.com/szfgnyNB

the pcap
[test265.pcap.zip](https://github.com/meetecho/janus-gateway/files/4554415/test265.pcap.zip)


the screen shot
Capture d’écran 2020-04-29 à 22 16 45

Capture d’écran 2020-04-29 à 22 21 54


However, regarding the CPU and GPU usage, I can't notice a huge difference :(

**Comment by trankkilou** [comment]
the echo test also works on the iPhone (no idea is hardware acceleration is enable) but in fullhd VP8 and H264 it seems to be close to CPU limit (being hot, seems to lag a little) and this is not the case here

IMG_1BA682445AC8-1

**Comment by trankkilou** [comment]
in videoroom, the MacBook with safari tech preview works also in H265. However the iPhone doesn't (in iOS 13.3.1), it proposes only VP8 and is not able to decode H265. I will try IOS 13.4.1 but if it still doesn't work , I think we will have to wait next IOS release .

**Comment by oscarvadillog** [comment]
Really nice! Have you tried the other demos @trankkilou ?

**Comment by trankkilou** [comment]
Full report here

https://github.com/meetecho/janus-gateway/pull/2120 <https://github.com/meetecho/janus-gateway/pull/2120>

**Comment by trankkilou** [comment]
> Really nice! Have you tried the other demos @trankkilou ?

by others demos you mean ?

**Comment by oscarvadillog** [comment]
Videocall, videoroom, recorder...

**Comment by lminiero** [comment]
Thans @trankkilou! I'll have a look later. In the meanwhile, thanks to @agouaillard we also have an AV1-compliant Chrome browser to use as well, which already led me to a first fix (I was using the wrong rtpmap in SDP). It's still not working for me, as I see some errors in the Chrome logs:

```
Failed to encode frame. Error code: -7
```

but I'll check later as it's likely I'm missing something in the negotiation.

**Comment by lminiero** [comment]
In case you want to test AV1 yourselves too, you can find more info here: https://twitter.com/agouaillard/status/1255584180055883776

**Comment by lminiero** [comment]
@trankkilou could you also provide me with an .mjr recording of the EchoTest session? It should be enough to type:

    echotest.send({message: {record: true}});

on the JavaScript console, and that will generate different mjrs in the Janus folder. I'd only need the video one, which would help me parse the RTP packets directly from the post-processor. Thanks!

**Comment by trankkilou** [comment]
Hi lorenzo

> echotest.send({message: {record: true}});
Sommes to be accepted
> echotest.send({message: {record: true}});
[Debug] Sending message to plugin (handle=3899926466393365): (janus.js, line 1300)
[Debug] {janus: "message", body: {record: true}, transaction: "jeFDSWOpQy7t"} (janus.js, line 1301)
< undefined
[Debug] Got an ack on session 4019270843830394 (janus.js, line 594)
[Debug] {janus: "ack", session_id: 4019270843830394, transaction: "jeFDSWOpQy7t", hint: "I'm taking my time!"} (janus.js, line 595)
[Debug] Message sent! (janus.js, line 1306)
[Debug] {janus: "ack", session_id: 4019270843830394, transaction: "jeFDSWOpQy7t", hint: "I'm taking my time!"} (janus.js, line 1307)
[Debug] Got a plugin event on session 4019270843830394 (janus.js, line 743)
[Debug] {janus: "event", session_id: 4019270843830394, transaction: "jeFDSWOpQy7t", sender: 3899926466393365, plugindata: {plugin: "janus.plugin.echotest", data: {echotest: "event", result: "ok"}}} (janus.js, line 744)
[Debug]   -- Event is coming from 3899926466393365 (janus.plugin.echotest) (janus.js, line 755)
[Debug] {echotest: "event", result: "ok"} (janus.js, line 757)


 but record nothing

I also try to hard code it in echo cfg & restart janus , same
general: {
	#events = false
	record = true
	filename = "/tmp/record-echo.mjr"
}

**Comment by lminiero** [comment]
You can specify a base path too, e.g.:

    echotest.send({message: {record: true, filename: "/tmp/prefix"}});

**Comment by trankkilou** [comment]
here you are ;)
[prefix-video.mjr.gz](https://github.com/meetecho/janus-gateway/files/4557267/prefix-video.mjr.gz)
[prefix-audio.mjr.gz](https://github.com/meetecho/janus-gateway/files/4557268/prefix-audio.mjr.gz)

**Comment by lminiero** [comment]
Thanks!

**Comment by lminiero** [comment]
@trankkilou looks like you saved a VP8 stream though?

**Comment by trankkilou** [comment]
Yes sorry my bad I forgot the ?vcodec=265. I m fixing my mistake stay tunes

**Comment by trankkilou** [comment]
Ok so the issue I have is my codec is h265
echotest.send({message: {record: true, filename: "/tmp/prefix"}});
Do nothing. In janus.log I have nothing neither


With other codecs it works like expected

J-

**Comment by lminiero** [comment]
I don't see any codec-specific thing in the EchoTest, and if I manually set "h265" in the `janus_recorder_create` call it works as expected, so the code in `record.c` is fine too. Do you see any error in the Janus logs?

**Comment by trankkilou** [comment]
Sorry for the delay , I have to reinstall janus on a new server at home
It seems the recording did work this time
[prefix-video.mjr.gz](https://github.com/meetecho/janus-gateway/files/4566766/prefix-video.mjr.gz)

**Comment by lminiero** [comment]
@trankkilou thanks! I can confirm I see the "h265" string in the recording header now :+1:

**Comment by lminiero** [comment]
I managed to get H.265 post-processing to work, which means @trankkilou should be able to convert his H.265 mjrs to .mp4 :slightly_smiling_face:  SPS parsing is the most atrocious invention of humanity, but eventually I did it... I'm pretty sure it will not really work in all cases (SPS parsing has many conditions, and I didn't explore them all), but it seems to work for the captures I had so I'm fine with it for now. I also added a simple way to detect H.265 keyframes in Janus too, which simply checks if the first NAL is a VPS or SPS: this works with the way Safari is packetizing RTP (VPS, SPS, PPS as separate packets), while it may not work if it's packetized differently, but I can't really say I care, since Safari is the only one doing it anyway.

For AV1, unfortunately I can't test yet myself (see issue I opened on CoSMo's repo above), and I don't have any pcap dump of RTP/AV1 packets to play with either, so until that happens I'm afraid there's not much I can do at the moment. I'll check if my FFmpeg/Gstreamer installations support it already to try and generate an RTP/AV1 stream to capture myself.

**Comment by lminiero** [comment]
Yay, I managed to get a capture of AV1 RTP packets! Since the browser doesn't work yet, I used the libwebrtc precompiled examples. It was a bit of a pain, as I had to create a fake `peerconnection_server` (in nodejs) to have a real `peerconnection_client` talk to the Janus EchoTest: this meant reverse-engineering their protocol, and trying to understand why things wouldn't work, but eventually I managed to do that, as you can see from this screenshot:

Screenshot_2020-05-12_19-59-31

Now I just have to dig into the bitstream and see if I can understand anything...

**Comment by lminiero** [comment]
Pinging @tmatth just to make him aware of this, since IIRC he's involved in AV1-related development as well in another context.

**Comment by lminiero** [comment]
Uff, finally managed to parse the AV1 Sequence Header too!

```
Counted 294 frame packets
  -- Detected new resolution: 320x240 (seq=1)
  -- Detected new resolution: 480x360 (seq=284)
```

The snippet above is from the mjr capture I have, where you can see it starts 320x240 and then increases a few frames later. As far as I'm concerned, this concludes the effort on this pull request, so I plan to merge soon.

**Comment by tmatth** [comment]
> Uff, finally managed to parse the AV1 Sequence Header too!
> 
> ```
> Counted 294 frame packets
>   -- Detected new resolution: 320x240 (seq=1)
>   -- Detected new resolution: 480x360 (seq=284)
> ```
> 
> The snippet above is from the mjr capture I have, where you can see it starts 320x240 and then increases a few frames later. As far as I'm concerned, this concludes the effort on this pull request, so I plan to merge soon.

BTW using https://github.com/dwbuiten/obuparse might be easier than rolling your own parsing.

**Comment by lminiero** [comment]
@tmatth thanks for the heads up. I'd rather not add that much code though, especially considering we only parse the SH OBU, and not all of them. If our dumb parser proves unreliable in the future, though, I'll consider integrating it instead.

**Comment by lminiero** [comment]
Merging as there's nothing else we can do for now.

**Pull request merged**
