### PR TITLE
fixed warning when used from C++ plugin

### PR DESCRIPTION
**Pull request by RSATom**
It's annoying a little bit...

### CODE REVIEW

**Comment by lminiero** [comment]
Not sure which warnings you're talking about, but if it makes your compiler happy... :smile: 
Can you sign our CLA by filling in the form at the [end of this page](https://cla.conf.meetecho.com/janus/) so that I can merge this?

Thanks!

**Comment by RSATom** [comment]
gcc just don't like when two string literals not separated by any whitespace, nothing more...
CLA signed.

**Comment by lminiero** [comment]
Did you fill the form, or just authenticate with Github? I don't see your name in the list.

**Comment by RSATom** [comment]
hm... maybe I did something wrong, let me check again... sorry

**Comment by RSATom** [comment]
Was closed page too quickly, missed additional fields to fill...
Now I hope I did it right...

**Comment by lminiero** [comment]
Thanks, merging!

**Pull request merged**
