### PR TITLE
feat(textroom): listparticipants

### PR DESCRIPTION
**Pull request by mtltechtemp**
Everything's in the title.

CLA signed.

### CODE REVIEW

**Comment by lminiero** [comment]
Thanks! I think `listparticipants` should ask for the `pin` if it's configured, though. It may be a password-protected room, and this way everyone can just see who's in even without it. I guess I'll have to do the same for other plugins, if it's missing there too.

**Comment by mtltechtemp** [comment]
@lminiero Good catch!
I'm not comfortable enough with the codebase to do that, I'm afraid I might create security holes.
But, feel free to modify my PR.

**Comment by lminiero** [comment]
> Edit: for AudioBridge, VideoRoom, no pin's required to list participants too.

Yep, that's why I said «I guess I'll have to do the same for other plugins, if it's missing there too» :smile: 

Anyway, that's fine. Since I can take care of that myself.

**Comment by lminiero** [comment]
Merging! :+1:

**Pull request merged**
